### ISSUE TITLE
global context not shown

### ISSUE THREAD

**Issue by andyprv** [node-red/node-red-docker#104]
Hello

## So you have a real issue to raise...
yes, think so 

### What are the steps to reproduce?
since 0.19.0  docker images , no (global) context shown on the right Editor Panel.

### What happens?
global context works , just fine , but Its hard to Debug, because there is no content shown 

### What do you expect to happen?
see the content of the context values 

![nodered_v18](https://user-images.githubusercontent.com/36567942/54919863-1e656080-4f02-11e9-968a-774e3d775eb4.png)

 

### Please tell us about your environment:

- [ ] Node-RED version: v19+
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS: Docker Image
- [ ] Browser: chrome latest update

**Comment by knolleary** [comment]
Hi,

Your screenshot shows the context browser contrib node in a pre 0.19 version of Node-RED 

0.19 introduced a builtin context sidebar panel that you should use instead

**Comment by andyprv** [comment]
Yes , I know that this is the pre 19 Version .. because the Issue Form says " what i expect" ..
that's what I expect ... that I shows the content of the context. 

Docker Images:latest   look like this: 
![2019-03-25_134422](https://user-images.githubusercontent.com/36567942/54920877-ac424b00-4f04-11e9-80c5-6b52d85a6e19.png)

some Flow / programm

meanwhile I checked the flow on a host installed version of NodeRed v20.x  on a Raspberry
there It looks fine:

![2019-03-25_135107](https://user-images.githubusercontent.com/36567942/54921106-37bbdc00-4f05-11e9-8a9f-f544f3f2bad8.png)
