### ISSUE TITLE
error Exit status 1 - error Failed at the node-red-docker@1.0.0 start script

### ISSUE THREAD

**Issue by nodecentral** [node-red/node-red-docker#108]
Hi

My nodered docker has stopped working today, will not stay on, please see error from the log - please let me know if there is anything I can do? (Docker is running under HOST, on QNAP Container Station) 

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--userDir',
1 verbose cli   '/data' ]
2 info using npm@6.4.1
3 info using node@v8.15.1
4 verbose config Skipping project config: /usr/src/node-red/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle node-red-docker@1.0.0~prestart: node-red-docker@1.0.0
7 info lifecycle node-red-docker@1.0.0~start: node-red-docker@1.0.0
8 verbose lifecycle node-red-docker@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle node-red-docker@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle node-red-docker@1.0.0~start: CWD: /usr/src/node-red
11 silly lifecycle node-red-docker@1.0.0~start: Args: [ '-c',
11 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"' ]
12 silly lifecycle node-red-docker@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
14 verbose stack Error: node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:915:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid node-red-docker@1.0.0
16 verbose cwd /usr/src/node-red
17 verbose Linux 4.2.8
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
19 verbose node v8.15.1
20 verbose npm  v6.4.1
21 error code ELIFECYCLE
22 error errno 1
23 error node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
23 error Exit status 1
24 error Failed at the node-red-docker@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by nodecentral** [comment]
Ok, by replacing the current flow.json with an older version, it does not return the error anymore.  There is obviously something in the flow that was causing it to crash/fail. 

The only module I can recall installing was the Sonos Polly one, which for now i’m going to assume is the cause, how it was doing it - I’m not sure.

**Comment by dceejay** [comment]
closing this as it seems to have been fixed by the user.
