### ISSUE TITLE
Projects feature not available in the slim container

### ISSUE THREAD

**Issue by rcarmo** [node-red/node-red-docker#110]
### What are the steps to reproduce?

I have tried to use the `nodered/node-red-docker:0.20.5-slim-v10` container to set up the ["projects" feature](https://nodered.org/docs/user-guide/projects/), but it is unable to set up projects because (apparently) it is missing the `git` binary.

### What happens?

I see a mention about `git` not being present in the container logs even though I have enabled the projects feature in `settings.js`

### What do you expect to happen?

I would expect the projects feature to be enabled regardless of the container runtime in use.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.5-slim-v10
- [x] node.js version: the one packed into the container
- [x] npm version: the one packed into the container
- [x] Platform/OS: Ubuntu x86_64 as Docker host, whatever is in the container as userland
- [x] Browser: any

**Comment by knolleary** [comment]
The slim image is a minimal image on purpose. It is intended for running a minimal Node-RED install.

**Comment by rcarmo** [comment]
The `git` package on Alpine is a mere 15MB installed. I can build a custom container, but since I need #109 to work for my use case, this would be both a workaround and an improvement in user experience.

**Comment by knolleary** [comment]
There is a separate question of whether we create images with projects pre-enabled. This is part of a wider review of our docker images and not something to handle as an issue.

**Comment by rcarmo** [comment]
I didn't see that listed as a ticket, so I thought there were no feature requests for it. Feel free to close this (or tag it accordingly as input to that review).

**Comment by RaymondMouthaan** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This closes this issue, as per default git is pre-installed in all images to support "Project feature"

There are a few changes to the new release, please read the README for further details.
