### ISSUE TITLE
docker build works, docker hub doesn't (aarch64)

### ISSUE THREAD

**Issue by dave93cab** [node-red/node-red-docker#117]
### What are the steps to reproduce?

pull from docker hub and 
`docker run -it --name nr -p 1880:1880 nodered/node-red-docker:latest`
results in:
`standard_init_linux.go:207: exec user process caused "exec format error"`

clone repo master branch,

`docker build -f latest/Dockerfile -t nodered:latest .` 

and:

`docker run -it --name nr -p 1880:1880 nodered:latest`

results in:
```
Welcome to Node-RED
===================
. . .
19 Jun 16:14:05 - [info] Started flows
```

### What do you expect to happen?

docker hub image would work as I believe node automatically detects architecture (i.e. aarch64 dockerfile in this repo is not required)

### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
Odroid N2 aarch64
Ubuntu 18.04
docker 18.09
- [ ] Browser:

**Comment by knolleary** [comment]
Docker does detect the architecture, but relies on the project having created suitable images for the architecture.

There is an open pr to address creating multi-architecture images that I believe would address this.

**Comment by PaulWieland** [comment]
I’m getting the same error on my raspberry pi 4. Is there a work around?

**Comment by RaymondMouthaan** [comment]
Hi guys, i am the creator of PR #127, if you guys like to try node-red images which are based upon #127, i like to invite you to check out my [docker hub](https://cloud.docker.com/repository/docker/raymondmm/node-red/general).

How to use the images can be found in the [README](https://github.com/RaymondMouthaan/node-red-docker/blob/master/README.md)

**Comment by dceejay** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red. 

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
