### ISSUE TITLE
container gets huge in space resulting in disk out of space

### ISSUE THREAD

**Issue by maartendel** [node-red/node-red-docker#123]
Hi, 

Running this container in docker, the container keeps growing in disk space. 
Anybody any idea why?

Regards, 
Maarten

**Comment by knolleary** [comment]
Can you not examine it to see for yourself? We've not had any similar reports.

**Comment by dceejay** [comment]
Any updates on this ? If not I'll close this issue as we have now shipped version 1.0.0 which is based on an Alpine multi-stage build so has many more tags and choices.

**Comment by jungi77** [comment]
I have noticed the same problem lately, but I'm  not sure if it is Node-Red's issue. I'm using the latest version of Node-Red  (and love it), Docker Desktop 4.10.0 (but tested it with higher versions too) on WIN10 21H2. 
When run my stack, it devours 100Gb of disk space in less than 24h, unless is stop Node-Red. You can see that effect in the attached picture, where I stopped Node-Red container around 9:00 and the disk space consumption immediately stopped. 

What can be done about that? 

![image](https://github.com/node-red/node-red-docker/assets/34880066/6aa05d69-bed5-4253-9f3c-5df34e0237ef)

**Comment by hardillb** [comment]
Same question, Have you inspected the container to see what is consuming the space?

If your flow is writing files to a location that is not a mounted volume, then the container is just going to grow, this is property of the flow you are running, not Node-RED.

**Comment by jungi77** [comment]
I haven't inspected the container, because I don't know what to look for yet - but it's a good call and I'll dig into that. 

I use the same flows; I created two years ago. I use bind mounts with Docker Desktop and my Node-Red flows only read/write data into an Influx DB, that runs in a separate container.  Where could I start looking for file writing operations?

**Comment by hardillb** [comment]
You will have to look at your flows for file write operations. But I now notice that you are not measuring the size of the container just that your hard disk is being consumed.

This leads to another option which is it is the logging from the container that is consuming the space. Docker just writes the output from the container to a file by default which would show the same behaviour. Have you looked at the logs from from the container, it could be that the upgrade has tripped up an old node that is now logging a lot (possibly errors).

**Comment by jungi77** [comment]
Container logging sounds promissing - in fact, I had events lately (like "no data available"), that produce tons of errors. I'll look into that!   Thanks!
