### ISSUE TITLE
Two issues testing raymondmm/node-red:latest-rpi

### ISSUE THREAD

**Issue by fabnavigator** [node-red/node-red-docker#125]
First of all. Thank you so much for this image! I was dead in the water without it.

I have two node-red containers. In the first case, Portainer is telling me that the container is unhealthy, but I didn't add a health check. Below is my compose text. Could it have something to do with my non-standard port? I didn't see this issue with the nodered/node-red-docker:0.20.7-rpi image. Besides being unhealthy, my flows seem to be working.

  node-red-bose:
    container_name: node-red-bose
    image: raymondmm/node-red:latest-rpi
    # image: nodered/node-red-docker:0.20.7-rpi
    user: '1001'
    ports:
      - 1881:1881
    volumes:
      - /home/fabnav/opt/node-red-bose:/data
      - /etc/localtime:/etc/localtime:ro

Below is the log file:
,
> node-red-docker@0.20.7 start /usr/src/node-red,
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data",
,
18 Aug 12:54:34 - [info] ,
,
Welcome to Node-RED,
===================,
,
18 Aug 12:54:34 - [info] Node-RED version: v0.20.7,
18 Aug 12:54:34 - [info] Node.js  version: v10.16.2,
18 Aug 12:54:34 - [info] Linux 4.19.58-v7+ arm LE,
18 Aug 12:54:35 - [info] Loading palette nodes,
18 Aug 12:54:38 - [info] Dashboard version 2.16.0 started at /ui,
18 Aug 12:54:39 - [info] Settings file  : /data/settings.js,
18 Aug 12:54:39 - [info] Context store  : 'default' [module=localfilesystem],
18 Aug 12:54:39 - [info] Context store  : 'memory' [module=memory],
18 Aug 12:54:39 - [info] User directory : /data,
18 Aug 12:54:39 - [warn] Projects disabled : editorTheme.projects.enabled=false,
18 Aug 12:54:39 - [info] Flows file     : /data/flows.json,
18 Aug 12:54:39 - [info] Server now running at http://127.0.0.1:1881/,
18 Aug 12:54:39 - [info] Starting flows,
18 Aug 12:54:39 - [info] Started flows,

My second container doesn't use a non-standard port, and isn't unhealthy. It uses timers though, and doesn't seem to be picking up the correct time zone, as the nodered/node-red-docker:0.20.7-rpi image did. Below is the compose text.

  node-red:
    container_name: node-red
    image: raymondmm/node-red:latest-rpi
    # image: nodered/node-red-docker:0.20.7-rpi
    depends_on:
      - postgres
      - home-assistant
    user: '1001'
    ports:
      - 1880:1880
    volumes:
      - /home/fabnav/opt/node-red:/data
      - /etc/localtime:/etc/localtime:ro

Below is the log file:
,
> node-red-docker@0.20.7 start /usr/src/node-red,
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data",
,
18 Aug 13:18:35 - [info] ,
,
Welcome to Node-RED,
===================,
,
18 Aug 13:18:35 - [info] Node-RED version: v0.20.7,
18 Aug 13:18:35 - [info] Node.js  version: v10.16.2,
18 Aug 13:18:35 - [info] Linux 4.19.58-v7+ arm LE,
18 Aug 13:18:36 - [info] Loading palette nodes,
18 Aug 13:18:41 - [info] Dashboard version 2.16.0 started at /ui,
18 Aug 13:18:41 - [info] Settings file  : /data/settings.js,
18 Aug 13:18:41 - [info] Context store  : 'default' [module=localfilesystem],
18 Aug 13:18:41 - [info] Context store  : 'memory' [module=memory],
18 Aug 13:18:41 - [info] User directory : /data,
18 Aug 13:18:41 - [warn] Projects disabled : editorTheme.projects.enabled=false,
18 Aug 13:18:41 - [info] Flows file     : /data/flows.json,
18 Aug 13:18:41 - [info] Server now running at http://127.0.0.1:1880/,
18 Aug 13:18:42 - [info] Starting flows,
18 Aug 13:18:42 - [info] [inject:18:00 on] crontab = 00 18 * * *,
18 Aug 13:18:42 - [info] [inject:20:00 on] crontab = 00 20 * * *,
18 Aug 13:18:42 - [info] [inject:01:30 off] crontab = 30 01 * * *,
18 Aug 13:18:42 - [info] [inject:6:00] crontab = 00 06 * * *,
18 Aug 13:18:42 - [info] [inject:5:00] crontab = 00 05 * * *,
18 Aug 13:18:42 - [info] [inject:9:00 on] crontab = 00 09 * * *,
18 Aug 13:18:42 - [info] [inject:daily initialization to false] crontab = 00 18 * * *,
18 Aug 13:18:42 - [info] [inject:19:00] crontab = 00 19 * * *,
18 Aug 13:18:42 - [info] [inject:22:00] crontab = 00 22 * * *,
18 Aug 13:18:43 - [info] [inject:midnight] crontab = 01 00 * * *,
18 Aug 13:18:43 - [info] Started flows,
18 Aug 13:18:43 - [info] [server:Home Assistant] WebSocket Connected to http://home-assistant:8123,

Thanks,

Bill

**Comment by knolleary** [comment]
This is the repo for the official Node-RED docker images.

If you want to report an issue against a different image, then raise it against that image's repo.

In this instance, we are looking to merge the changes in the other image into the official images. But you should still report issues against the right repo until those changes have been merged here and we have published an update.

**Comment by fabnavigator** [comment]
Oops. I'm sorry. I'mm do that.

**Comment by fabnavigator** [comment]
Reported to wrong repository.
