### ISSUE TITLE
Settings.json - flowFile ignored due to ENV

### ISSUE THREAD

**Issue by dvdvnl** [node-red/node-red-docker#128]
### What are the steps to reproduce?

1. Create a custom `settings.json` file, or copy the default one.
2. Add or uncomment the `flowFile` property and set a random value.
3. Create a Dockerfile from the `nodered/node-red-docker` image (v8 or v10) and copy the custom `settings.json` into the image.
4. Build the image.
5. Run a container with the new image.

### What happens?
Upon the start of Node-Red the `flowFile` property from the `settings.json` file is not considered. The console output shows that the used "Flows file" is `/data/flows.json`, independently from the value of  `flowFile`.

Other settings (e.g. `editorTheme.projects.enabled`) are considered, so the `settings.json` file is invoked correctly.

However, in the base image's Dockerfile ([node-red-docker/latest/Dockerfile](https://github.com/node-red/node-red-docker/blob/4fd70221a59d18f023d46b438025d657f193cbb1/latest/Dockerfile#L27)) there's the definition of the ENV "Flows" that overwrites the `flowFile` property:
```
ENV FLOWS=flows.json
```
Changing the ENV value in the custom Dockerfile has the desired effect described below.

### What do you expect to happen?
The used "Flows file" should be the file specified in the `settings.json` file, the value of the  `flowFile` property.

### Please tell us about your environment:

- [x] Node-RED version: v0.20.7
- [x] node.js version: v8.16.0, v10.16.0
- [x] npm version: 6.4.1, 6.9.0
- [x] Platform/OS:  nodered/node-red-docker:v8, nodered/node-red-docker:v10
- [ ] Browser:

**Comment by knolleary** [comment]
This is working as designed. The env property takes precedence if it is set. If you set it to an empty string in your own image it should be ignored and it will then use the value from your settings file.

**Comment by dvdvnl** [comment]
Thank you for your reply. I suppose it is designed this way to easily change the flows file when running Node-Red via `docker run` by simply providing an environmental variable.
However, setting a default value to the ENV in the Dockerfile makes the property in the settings file obsolete. Do you think a hint, with the information you provided in your comment, in the readme file might be a good idea?

**Comment by dceejay** [comment]
you can also add `-e FLOWS=""` to your run command - which effectively nulls the FLOWS override and lets the settings.js work as you want.

Closing as not intending to fix further.
