### ISSUE TITLE
Architecture support for aarch64 (ARMv8)

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red-docker#13]
Pull request #12 includes a Dockerfile for support for Node-RED on aarch64 (ARMv8) architectures. It is experimental, to the point where I'm not sure that the Travis environment can even test it. 

The base image is from https://hub.docker.com/r/aarch64/node/

**Comment by jthomas** [comment]
Thanks for raising this. Have you been able to successfully build and test these out? 
Travis CI doesn't support building ARM architectures, I have to manually build the images locally and push them to Docker Hub.
Which platforms do these images enable?

**Comment by vielmetti** [comment]
Thanks @jthomas . The test that I did was on a pre-release ARMv8 96-core machine from a hosting provider; it runs this:

```
root@armv8hello:~# uname -a
Linux armv8hello.local.lan 4.4.0-38-generic #57-Ubuntu SMP Wed Sep 7 10:19:14 UTC 2016 aarch64 aarch64 aarch64 GNU/Linux
root@armv8hello:~# cat /proc/version
Linux version 4.4.0-38-generic (buildd@bos01-arm64-006) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.2) ) #57-Ubuntu SMP Wed Sep 7 10:19:14 UTC 2016
```

Let me know what test suite would be useful to use against this!

**Comment by jthomas** [comment]
As it works, I'm happy to put this in.
I'll update the manual build scripts to pushing this tag to Docker Hub.
