### ISSUE TITLE
Container 'nodered/node-red' doesn't exist on Docker Hub

### ISSUE THREAD

**Issue by pkjq** [node-red/node-red-docker#131]
New container of node-red doesn't exist on Docker Hub.
https://hub.docker.com/r/nodered/node-red/ returns 404 error.

**Comment by dceejay** [comment]
Correct - we haven't released version 1.0 yet....

**Comment by knolleary** [comment]
Hi @pkjq 

you've caught us in the middle of a big update. The repo has been updated for the new images we'll be publishing for 1.0 in the near future.

For the existing images, please refer to the docs here: https://nodered.org/docs/getting-started/docker

**Comment by dceejay** [comment]
As the readme says the older / current images are here - https://hub.docker.com/r/nodered/node-red-docker

**Comment by PedroLamas** [comment]
I noticed this same issue and was about to open an issues when I spotted this one... might be worth keeping this ticket open for now to avoid duplication!

**Comment by RaymondMouthaan** [comment]
We are on it .. a little more patience please :-)

**Comment by dceejay** [comment]
Closed now. Node-RED 1.0.0 released.
