### ISSUE TITLE
Can't see all tags on Synology

### ISSUE THREAD

**Issue by natcl** [node-red/node-red-docker#14]
I'm not sure if it's a bug with the Synology OS or a quirk with Docker's registry hub but I can only see the 0.14.5 and 0.14.5-slim tags when I try to install Node-RED from Synology, see image:
<img width="536" alt="capture" src="https://cloud.githubusercontent.com/assets/77556/19390488/52e1b974-91f6-11e6-9858-ebb4bc03288d.PNG">

**Comment by jthomas** [comment]
I wonder if there's a caching issue.... 
This is a bug to raise with the Synology project if possible. 
Given the tags are shown in the public Docker Hub repository, I'm not sure this is an issue under our control.

**Comment by natcl** [comment]
Thanks, will try to see if I can send them an issue !

Le ven. 14 oct. 2016 à 11:32, James Thomas <notifications@github.com> a
écrit :

**Comment by natcl** [comment]
Small update:
Contacted Synology and they basically told me the problem is with Docker so might not be an easy fix...

```
Hello,

 

Thank you for contacting Synology Support.

Are you running the latest version of Docker 1.11.2? If not you will want to update to the latest version. 

I would suggest checking with docker support on this issue since our side of docker support really is limited to making sure the package is installed and able to connect.

Feel free to reply to this email if you have any further questions or issues.

 

Have a great day, 

Ryan
```

**Comment by natcl** [comment]
Another update, apparently it's a bug that'll eventually get fixed:

```
Hello,

 

Our developers have informed me that this is a known bug with Docker Hub and will be fixed in Docker v.0269. 

If you want to download the latest version of the image, they have recommended that you run the following command under SSH:

docker pull
```
