### ISSUE TITLE
docker commit does not work

### ISSUE THREAD

**Issue by JmStawikowski** [node-red/node-red-docker#141]
**Saving Changes As Custom Image does not work**
https://github.com/node-red/node-red-docker#saving-changes-as-custom-image

To run in Docker in its simplest form just run:

    docker run -it -p 1880:1880 --name mynodered nodered/node-red:latest-minimal

Docker allows you to the current state of a container to a new image. This means you can persist your changes as a new image that can be shared on other systems.

    $ docker commit mynodered custom-node-red

Does not work:

This means that you can not persist your changes as a new image

**Comment by knolleary** [comment]
We provide an issue template for you to use to ensure enough information is provided so we can quickly understand the issue you are raising.

When you say it does not work, what do you mean? Do you hit an error? What happens when you run that command?

**Comment by JmStawikowski** [comment]
The new image does not have the data

**Comment by RaymondMouthaan** [comment]
Confirmed that `docker commit` does not  save the changes.

- reason for this: is that the node-red container saves data into `/data` inside the container, however this dir is defined as `VOLUME` to persist outside the container. If no `-v` (or equivalent) has been given to the `docker run` command, docker still creates a volume to persists the data outside the container. This works as designed by Docker.

**Comment by dceejay** [comment]
But does it save other changes ? (though I guess extra nodes etc are also in the /data dir)

**Comment by RaymondMouthaan** [comment]
`/usr/src/node-red` is not a `VOLUME` and extra nodes get installed here - those should be saved with `docker commit`, but haven't tested it.

**Comment by dceejay** [comment]
Just checked and extra nodes installed via palette end up in /data. So should be all good if all persisted outside.

**Comment by JmStawikowski** [comment]
**docker commit**
Description: Create a new image from a container’s changes
https://docs.docker.com/engine/reference/commandline/commit/

With the old version of Node-RED docker (**nodered/node-red-docker**) this was possible !
https://hub.docker.com/r/nodered/node-red-docker

For example:
1. docker run -it -p 1880:1880 --name **mynodered** nodered/node-red-docker
2. container’s changes : modification of flow **mynodered** with Node-RED  
3. docker commit **mynodered** custom-node-red
4. docker run -it -p 8001:1880 --name mynodered1 custom-node-red
5. docker run -it -p 8002:1880 --name mynodered2 custom-node-red

Another example:
With Portainer.io (**https://www.portainer.io/**)
Create image:
You can create an image from this container, this allows you to backup important data or save helpful configurations. You'll be able to spin up another container based on this image afterward.
https://drive.google.com/drive/folders/1tNihHF7HHmDeld41NcFDeq02q50KQJI5?usp=sharing

**Comment by RaymondMouthaan** [comment]
Read the section `Extended description` from your link [docker commit](https://docs.docker.com/engine/reference/commandline/commit/)

> **It can be useful to commit a container’s file changes or settings into a new image. This allows you to debug a container by running an interactive shell, or to export a working dataset to another server. Generally, it is better to use Dockerfiles to manage your images in a documented and maintainable way. Read more about valid image names and tags.**

> **The commit operation will not include any data contained in volumes mounted inside the container.**

A possible solution for you might be > [commit-content-of-mounted-volumes-as-well](https://stackoverflow.com/questions/46349071/commit-content-of-mounted-volumes-as-well)

It used to work with the old images of `nodered/node-red-docker`, simple because those images were built without `VOLUME` defined in the Dockerfile. It's been added to the new images -exactly for this reason : 

> **reason for this: is that the node-red container saves data into /data inside the container, however this dir is defined as VOLUME to persist outside the container. If no -v (or equivalent) has been given to the docker run command, docker still creates a volume to persists the data outside the container. This works as designed by Docker.**

**Comment by JmStawikowski** [comment]
I thank you very much for your answer.

My confusion is that I used images that were built without VOLUME defined in the Dockerfile file with "docker commit"

Unfortunately, this feature is not available. 
With a tool based on a graphical interface like Portainer, this feature would authorize the creation of images Node-RED with the purpose of deploying them with Docker Swarm for example (Portainer and low-code/no-code)

I thank you very much

**Comment by dceejay** [comment]
If this is a feature you think we should have then lets move this discussion to the discourse forum - and talk it through how best to support it. We do want to support customed docker images as best we can.

**Comment by JmStawikowski** [comment]
Thank you very much.
No, with the new version of Node-RED, I will use a file Dockerfile to create my custom image.
Best Regards.

**Comment by dceejay** [comment]
Great - any further ideas or issues - see you over there.
