### ISSUE TITLE
Container won't start on RPI Zero W running Raspbian Buster

### ISSUE THREAD

**Issue by tms0** [node-red/node-red-docker#150]
### What are the steps to reproduce?

- Install latest stable docker version (19.03.3, build a872fc2) with containerd version 1.2.10.
- Run the given command `    docker run -it -p 1880:1880 --name mynodered nodered/node-red` 

### What happens?

- Container exits with status 139, with no logs.

### What do you expect to happen?

A working container ;-)

Note : I tried the old image (nodered/node-red-docker:rpi) and it worked perfectly (but with an outdated node.js version).

### Please tell us about your environment:

[ ] Platform/OS: RPI Zero W with a fresh install of the latest version of Raspbian Buster

[ ] Browser:
 
  - If you are a command line user please execute the following command and attach the log file.

    ```shell
    docker inspect <container_id> > container.log
    ```
  
[container.log](https://github.com/node-red/node-red-docker/files/3718729/container.log)

**Comment by RaymondMouthaan** [comment]
Hi @tms0,

Try one of the following command, where explicit tags are used for arm32v6.

```
docker run -it -p 1880:1880 --name mynodered nodered/node-red:1.0.1-12-minimal-arm32v6
```

or 

```
docker run -it -p 1880:1880 --name mynodered nodered/node-red:1.0.1-12-arm32v6
```

Let me know if that works for you.

Ray

**Comment by tms0** [comment]
Hi @RaymondMouthaan,

Thanks, it works with the explicit tag !
That will do the trick for me now, but I guess it's not the expected behavior ?

tms

**Comment by RaymondMouthaan** [comment]
Hi @tms0,

Glad it worked out for you, using explicit tags for arm32v6 on Raspberry Zero. Expected behaviour would be that Docker pulls automatically the correct arm32v6 image for you, instead of pulling arm32v7, however it doesn't. It's a docker issue as described here [moby#37647](https://github.com/moby/moby/issues/37647)

**Comment by tms0** [comment]
Good to know, thank you !

As a workaround, do you think it's possible to add rpi tags like in the deprecated repository ? This way we can get the latest image for rpis easily.

Regards,
tms

**Comment by RaymondMouthaan** [comment]
In case of non rpi zero, docker pulls the right image. Tested on a rpi 3b with Raspbian (32bit) and Ubuntu Server (64bit), where Docker respectively pulls arm32v7 and arm64v8. So the issue only occurs on rpi zero. 

Given the above, I'll consider to add a tags related to Raspberry Pi Zero.

**Comment by dceejay** [comment]
Not sure we want to add specific labels like this when it's an upstream problem that should get fixed. Once we have them we can't then easily remove them later. (well we can but it would upset users). 

I think maybe we just add extra docs for now - to both the Readme and the dockerhub page ?

**Comment by RaymondMouthaan** [comment]
@dceejay, I agree - some extra lines in the docs would help Raspberry zero users, without define specific tags in the Node-RED repo.

One remark to this: there is no 'latest' like tag for `arm32v6` specific images, which means Raspberry PI Zero users always need to change the full image tag if they want to update to a newer version.

**Comment by dceejay** [comment]
ok - noted. Will have a go at it later.

**Comment by dceejay** [comment]
Ok have added some Note: to all the READMEs
will leave open so we remember to check upstream

**Comment by tms0** [comment]
Hi,

Did you see this comment https://github.com/moby/moby/issues/34875#issuecomment-331017356 ? It seems like reordering the manifest can fix this issue.

**Comment by dceejay** [comment]
oh good find - worth a try ? @RaymondMouthaan  ?

**Comment by dceejay** [comment]
hmm - ours look like this - so v6 is already ahead of v7
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2419,
         "digest": "sha256:1a60576578f2dab7e813c14be7448223ade6591c5d8d183c181b59aa1a10bb7b",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2419,
         "digest": "sha256:8175e15337195d2daa67623fe84b4c9c3d5ac9bedea8a0493fa85ef9694f35de",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v6"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2418,
         "digest": "sha256:bdb6962803a722c457e60b27f079468c59129f778333daf278c0819f7c0ec4d0",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2419,
         "digest": "sha256:6cdefce9f8f4f7ff5d1ae2b8df3fcd5bd64d8611bf8c6dc4d836c57016561851",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2419,
         "digest": "sha256:61c641969dc254e600336e575fffff293f2ae42ca21005d04428ee23db482a02",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by tms0** [comment]
Hi,

@dceejay, there is a new proposed workaround : https://github.com/moby/moby/issues/34875#issuecomment-602140402

Can you have a look please ?

**Comment by dceejay** [comment]
if you have time to test it and provide a pull request that would be good. The comments following that still say it is not recommended.

**Comment by dceejay** [comment]
My testing today - via node-red/node-red-dev - setting the variant to v6l - still loaded the v7 for pizero - so by all means prove me wrong and show me how, but I have now looked.
Still needs to be fixed upstream

**Comment by tms0** [comment]
Sorry, I didn't mean to waste your time, thanks for trying !

**Comment by dceejay** [comment]
Not a problem - if you do find a fix and manage to get it to work - please do let us know.

**Comment by RaymondMouthaan** [comment]
Just came across this (still) open issue and notice that moby/moby#34875 has been merged just 4 days ago, perhaps worth trying?

**Comment by dceejay** [comment]
I see several thing being merged in that thread. I thought I tried the proposed workaround a few comments above and it didn't work... what has been merged to now make it work ?

**Comment by tms0** [comment]
Hi @dceejay,

I can confirm now it works on my rpi zero (Docker version 20.10.6, build 370c289 / containerd containerd.io 1.4.4) :

```console
$ docker run --rm nodered/node-red:latest

> node-red-docker@1.3.4 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"

3 May 09:32:05 - [info]

Welcome to Node-RED
===================

....
```

I think the fix is this one : https://github.com/containerd/containerd/pull/4530

**Comment by dceejay** [comment]
Sweet ! So Ok to close this now then :-)
