### ISSUE TITLE
synology docker install ffmpeg

### ISSUE THREAD

**Issue by pcherkash** [node-red/node-red-docker#156]
When installing ffmpeg package via synology visual interface I get an error:

https://prnt.sc/po2bra

bash-4.4$ apk add ffmpeg                                                                                                   
ERROR: Unable to lock database: Permission denied                                                                          
ERROR: Failed to open apk database: Permission denied  

how to solve this problem?

**Comment by dceejay** [comment]
As per the Issue template you deleted - we prefer general how-to type questions via the discourse forum or slack channel so the widest possible audience can offer help.
Permission errors are usually down to the fact that the default user is called node-red and not root.

**Comment by RaymondMouthaan** [comment]
@pcherkash,

Try the following command instead:

```
apk add --no-cache ffmpeg 
```

If that doesnt work, log in to the container as root:

```
docker exec -it --user root <container_id> /bin/bash
```

And try the above command again.
