### ISSUE TITLE
openSSH-server may not be needed

### ISSUE THREAD

**Issue by CTGControls** [node-red/node-red-docker#158]
First thank you for accepting my pull request. This helps tremendously. In my PR https://github.com/node-red/node-red-docker/pull/157 I noted that it maybe a typo to add openSSH-server. Am I short sighted or is there a reason for having SSH in the package. In the Docker world normally you would not see  openSSH-server because you should be using other forms of communications to interact with the docker image. SSH Port is not exposed in the docker-compose file so makes me think this may have been a typo or used for development testing. 

It seems like this is bloat that just adds more attack surface.

Please correct me if there is some other node-red use for the SSH server that I am unaware of. 

If you would like I can do a PR to remove openSSH-server.

**Comment by dceejay** [comment]
As per the form you managed to delete - please use the discourse forum or slack channel for general discussions and requests - so we can keep the issues list for actual issues.

Several users do want to be able to ssh into their remote instance as if they were running as an "normal" machine so the ssh server is there to support that even if not exposed... not unlike the ssl tools are now there to support only a certain section of users :-)... Yes it's possibly bloat - but users are free to use the minimal build - or rebuild it fully custom if they wish -  being docker it's not a great hardship after all.

**Comment by CTGControls** [comment]
Its all good, I was just asking to make sure it was not a typo. Once again thank you for accepting my pull request it save me from building my own.
