### ISSUE TITLE
NodeRed 1.0.3 docker now slow to start

### ISSUE THREAD

**Issue by marc-gist** [node-red/node-red-docker#159]
### What are the steps to reproduce?

update docker from 1.0.2 to 1.0.3

### What happens?

Starting docker is about the same speed, however, docker then reports "starting" for a minute or two, then goes to "unhealthy" status; however all seems to work ok so far.

### What do you expect to happen?
start and report started basically immediately.

### Please tell us about your environment:
Ubuntu 18 LTS fully updated with docker official repository

 
![image](https://user-images.githubusercontent.com/4084427/71104063-34e6d280-2189-11ea-820f-311b3062ec24.png)

**Comment by dceejay** [comment]
We just added a simple healthcheck to the dockerfile
`HEALTHCHECK CMD curl http://localhost:1880/ || exit 1`
that uses the defaults of repeat every 30s and a  timeout of 30s
It is a) down to the docker framework to run this - and b) down to the tool you are using to refresh its view of this state - neither of which we have much control over. We aren't going to start spamming our own runtime with healthcheck requests. Happy to consider any better options you may suggest. You are also free to customise your own Dockerfile based on ours to remove the healthcheck (as it was in 1.0.2) - whereupon you won't get any status .

**Comment by marc-gist** [comment]
> We just added a simple healthcheck to the dockerfile
> `HEALTHCHECK CMD curl http://localhost:1880/ || exit 1`
> that uses the defaults of repeat every 30s and a timeout of 30s
> It is a) down to the docker framework to run this - and b) down to the tool you are using to refresh its view of this state - neither of which we have much control over. We aren't going to start spamming our own runtime with healthcheck requests. Happy to consider any better options you may suggest. You are also free to customise your own Dockerfile based on ours to remove the healthcheck (as it was in 1.0.2) - whereupon you won't get any status .

Thanks for the info; however, i'm confused... you just added now to an update, or in v1.0.3?

doing > `docker ps`  also shows the "unhealthy" in the status column... so why would it be saying "unhealthy" if you have implemented a health check?

**Comment by marc-gist** [comment]
Something else I noticed... that curl command goes to "http", and I have nodered running under https... could that be the cause?  how do I update the URL?

**Comment by dceejay** [comment]
it's run inside the container so http should be ok. 
If you need to change it then yes you need to edit the dockerfile

**Comment by marc-gist** [comment]
> it's run inside the container so http should be ok.

But its not ok :( 
going into the shell of the docker, running the curl command, it indeed fails due to `https` being setup via settings files.
using `curl -k https://localhost:1880` works.

i'd rather not have to keep my own version of NodeRed docker.. nothing dev can do to set health check to https if needed and/or drop it again and make it an other for others than need it in this manner?

**Comment by dceejay** [comment]
aren't you already changing it to run https inside the container ?

**Comment by marc-gist** [comment]
No, its a change in the `settings.js` file to get https running.

**Comment by knolleary** [comment]
Thanks for reporting @marc-gist 

You are right the healthcheck doesn't take into account whether node-red has been configured to use https or not.

The quick fix is to remove the healthcheck, which I'll do now as we want to rebuild for the latest node security release anyway.

We do want to have a working healthcheck in there at some point - it just needs to be a bit smarter.
