### ISSUE TITLE
'Input:inject' of type 'Repeat - at a specific time' not working

### ISSUE THREAD

**Issue by rajr0** [node-red/node-red-docker#16]
I think, in order for 'Input:inject' of type 'Repeat - at a specific time' (Time-of-Day) to work, 'cron' needed to be installed inside the docker.
I had to add in the Dockerfile the following line
'RUN apt-get install -y cron'

I'm using the Node-RED container to control many switches at specific times; for eg:- turn on/off FishTank light.

$ docker run -it --rm hypriot/rpi-node:4 bash
root@44b3c8a909c0:/# cron
bash: cron: command not found
root@44b3c8a909c0:/#

**Comment by knolleary** [comment]
The inject node does not use the external cron command. Does the 'inject at specific time' option not work for you then? What have you tried?

**Comment by vielmetti** [comment]
Note that Docker on some systems is prone to clock drift. Two instances of people seeing this:

https://github.com/mist64/xhyve/issues/46
https://forums.docker.com/t/time-in-container-is-out-of-sync/16566

**Comment by jthomas** [comment]
Hello @rajr0, 

Are you still having issues with this? If so, can you help us by answering Nick's questions.

**Comment by albertskog** [comment]
Hi! I have the same issue with repeat at a specific time not working on my Raspberry Pi (not running the Docker image)!

**Comment by jthomas** [comment]
@albertskog does it run at all or just at a later or earlier time?

**Comment by albertskog** [comment]
From what I can tell so far it never runs automatically, just when I press the button on the node.

**Comment by techr** [comment]
[
    {
        "id": "4a97f20f.161c6c",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "a4f30c22.14802",
        "type": "inject",
        "z": "4a97f20f.161c6c",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "55 22 * * *",
        "once": false,
        "x": 110,
        "y": 60,
        "wires": [
            [
                "8ac23610.84b048"
            ]
        ]
    },
    {
        "id": "8ac23610.84b048",
        "type": "debug",
        "z": "4a97f20f.161c6c",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 307.16668701171875,
        "y": 62,
        "wires": []
    }
]
does not generate any output

**Comment by dceejay** [comment]
does the docker container even have a cron process daemon ?

**Comment by knolleary** [comment]
@dceejay I refer you to my previous comment - the Inject node doesn't have any dependency on the cron system command.

**Comment by dceejay** [comment]
ah yes - though the node-cron issue list does have some interesting issues that may be relevant
https://github.com/kelektiv/node-cron/issues

**Comment by NodeGuy** [comment]
I had this problem too.  I fixed it by changing the timezone on my host and then rebooting.

**Comment by RaymondMouthaan** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.

**Comment by ryanrdetzel** [comment]
Are we sure this is closed with 1.0? I'm having issues with inject in the official 1.0 docker.

**Comment by RaymondMouthaan** [comment]
@ryanrdetzel, can you provide the flow (json) so I can test it?

**Comment by ryanrdetzel** [comment]
I don't even see node-cron in the node_modules.
bash-4.4$ ls node_modules/no
node-pre-gyp/       node-red/           node-red-node-rbe/  node-red-node-tail/ nopt/
bash-4.4$ ls node_modules/no

**Comment by dceejay** [comment]
the node-cron package is in the core of node-red so will have been minified by the build step. It installs as node_modules/cron

**Comment by RaymondMouthaan** [comment]
I just tested your flow and it works as expected.

The steps I took:

1) Create a new test container with timezone set to Europe/Amsterdam:

```shell
docker run -it -e TZ=Europe/Amsterdam -p 1880:1880 nodered/node-red:latest
```

2) Imported the flow you supplied.

3) Modified the `time` at in the inject node to trigger it soon.

![Screen Shot 2019-10-02 at 13 35 33](https://user-images.githubusercontent.com/25717738/66041215-a6fc3380-e519-11e9-9164-cb7f5fc1336f.png)

__note__ clicking in the debug node on the timestamp changes the way the time shows.

**Comment by ryanrdetzel** [comment]
Thanks, I tried that command and it did work so I pulled down the images again and it seems to be fixed. Not sure what happened as I was on 1.0.0 and I'm still on 1.0.0 now but it's working. 🤷‍♂

**Comment by RaymondMouthaan** [comment]
> Thanks, I tried that command and it did work so I pulled down the images again and it seems to be fixed. Not sure what happened as I was on 1.0.0 and I'm still on 1.0.0 now but it's working. 🤷‍♂

Version of NR did not change, the code of NR did not change only a permission issues was solved.

Did you use `-e TZ=<your_timezone>` in your previous command?

**Comment by dceejay** [comment]
https://discourse.nodered.org/t/inject-at-a-a-specific-time-isnt-working-with-1-0/16194

**Comment by pm-mic** [comment]
I just ran into this issue and needed somewhat more time to get it fixed, and barely anywhere a working answer was provided. Someone mentioned somewhere that you either need to set the variable TZ or you need to link the timezone folders, but not both. In no way could I get the TZ variable to work, but the folder linking did it. For anyone else running into this issue, here is my docker-compose for running mosquitto and node-red with the proper timezone on raspbian buster:

version: "3"
services:
  broker:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - localnet
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  node-red:
    container_name: node-red
    depends_on:
      - broker
    image: nodered/node-red
    volumes:
      - "./node-red:/data"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    user: "0"
    networks:
      - localnet
    ports:
      - "1880:1880"
    restart: unless-stopped
networks:
  localnet:
