### ISSUE TITLE
How can I use a USB stick?

### ISSUE THREAD

**Issue by Schmello** [node-red/node-red-docker#160]
I have NodeRed running on my Synology in Docker.
I want to use a USB stick 868mhz.
I have entered device / dev / ttyACM0 in the environment variable. But the stick is not recognized.

![Bildschirmfoto 2019-12-25 um 22 04 54](https://user-images.githubusercontent.com/22894811/71450454-a6fb8080-2762-11ea-8477-d5c09369c13f.png)

**Comment by knolleary** [comment]
As described in the issue template you've deleted, please use the Node-RED forum for general how-to type questions: discourse.nodered.org

Thanks.
