### ISSUE TITLE
Support for SSL to utilize OPC UA Flows

### ISSUE THREAD

**Issue by chrisgray13247** [node-red/node-red-docker#161]
Installed the OPC UA flow and discovered (https://flows.nodered.org/node/node-red-contrib-opcua) the following event log issue:

########################################### OPENSSL ERROR ###########################################
2020-01-03T02:07:37.148Z [err] CWD = .
2020-01-03T02:07:37.149Z [err] Command failed: "openssl" version
2020-01-03T02:07:37.149Z [err] /bin/sh: openssl: not found

From what I can tell the version of node-red docker container OS does not support openssl.  Is this something that can be remedied or added?  (Current environment that I am running the container on is a Raspberry PI 4).

**Comment by dceejay** [comment]
I think we have already added it to our dev branch... (that is also available via dockerhub here - https://hub.docker.com/r/nodered/node-red-dev)  - please feel free to try it and comment.
(Note: don't use this for production as we may add/change/break things in there for testing)

**Comment by jhottell** [comment]
Here is a work around in any rate to get openssl installed during the build.
Add this to your Dockerfile,

> USER root
> RUN apk add --update openssl && rm -rf /var/cache/apk/*

**Comment by dceejay** [comment]
Should be closed by  latest release 25709996c2e7dde2aca89a81bd6c69811cb85112
