### ISSUE TITLE
auto kill 

### ISSUE THREAD

**Issue by maoguoxu** [node-red/node-red-docker#163]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--userDir',
1 verbose cli   '/data' ]
2 info using npm@6.13.4
3 info using node@v10.18.0
4 verbose config Skipping project config: /usr/src/node-red/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle node-red-docker@1.0.3~prestart: node-red-docker@1.0.3
7 info lifecycle node-red-docker@1.0.3~start: node-red-docker@1.0.3
8 verbose lifecycle node-red-docker@1.0.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle node-red-docker@1.0.3~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle node-red-docker@1.0.3~start: CWD: /usr/src/node-red
11 silly lifecycle node-red-docker@1.0.3~start: Args: [ '-c',
11 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"' ]
12 silly lifecycle node-red-docker@1.0.3~start: Returned: code: 1  signal: null
13 info lifecycle node-red-docker@1.0.3~start: Failed to exec start script
14 verbose stack Error: node-red-docker@1.0.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid node-red-docker@1.0.3
16 verbose cwd /usr/src/node-red
17 verbose Linux 3.10.0-327.el7.x86_64
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
19 verbose node v10.18.0
20 verbose npm  v6.13.4
21 error code ELIFECYCLE
22 error errno 1
23 error node-red-docker@1.0.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
23 error Exit status 1
24 error Failed at the node-red-docker@1.0.3 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by dceejay** [comment]
As per the form you have managed to delete we prefer general how to questions via the discourse forum mailing list. The dump above gives no context as to what you are doing to generate this error - or where or how you are trying to run it.  It may be something in your flow that is breaking it in which case you may need to start in safe mode so you can edit the flow before deploying. Our docker docs describe how to do this when running under docker by setting an environment variable at start time.
