### ISSUE TITLE
healthcheck fails when using https

### ISSUE THREAD

**Issue by adam-mckee** [node-red/node-red-docker#164]
when utilizing https with certificates, the healthcheck fails because it is configured to use localhost instead of the domain that would actually be in the certificate

### What are the steps to reproduce?
  1. Configure settings.js to utilize ssl certificate
  2. launch container
  3. notice that container never becomes healthy

### What happens?
the container never gets to a healthy state due to the healthcheck pinning to localhost.

### What do you expect to happen?
healthcheck either ignoring the host that is in the certificate or allowing me to specify what host should be in the certificate
### Please tell us about your environment:

[ ] Platform/OS:
ubuntu
[ ] Browser:
 not related, but chrome/firefox/safari

[nodered.txt](https://github.com/node-red/node-red-docker/files/4176358/nodered.txt)

**Comment by dceejay** [comment]
do you know which http error it is returning ?

**Comment by dceejay** [comment]
Are you using a real cert or self-signed ?
Is Authentication also switched on ? (configured)

**Comment by adam-mckee** [comment]
I'm using a real cert.  The cert contains the FQDN that node red should be accessible under (nodered.mydomain.com) and *not* localhost.  Here is a snippet from the error:

`ERROR { Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.mydomain.com, DNS:mydomain.com
    at Object.checkServerIdentity (tls.js:239:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1068:27)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
  reason:
   'Host: localhost. is not in the cert\'s altnames: DNS:*.mydomain.com, DNS:mydomain.com',
  host: 'localhost',`

**Comment by adam-mckee** [comment]
Also, authentication is not switched on (mydomain.com is only accessible internally).

**Comment by dceejay** [comment]
I have tried turning off the cert check in the healthcheck in the dev branch here - https://hub.docker.com/r/nodered/node-red-dev
any chance you can give that a try ?

**Comment by adam-mckee** [comment]
Works great!  Thank you for the quick turnaround.

**Comment by dceejay** [comment]
Thanks.
