### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by ferenczp** [node-red/node-red-docker#171]
Dear All,

I cannot install canvas on my Nodered container.
I would like to use it to create chart, and put it in a PDF document.

To reproduce use this command
npm install chartjs-node-canvas chart.js

Thank you for your help
Best regards

**Comment by dceejay** [comment]
As per the Issue template you have managed to delete - we prefer general how-to questions via either slack or the discourse forum.

You may need to be in the correct /data directory - but that will depend how you have mounted it - 
https://ibm.webex.com/ibm/j.php?MTID=m061a3b96ab680e3d2c6797e57a6e3407
