### ISSUE TITLE
Image bumped to 1.0.4 show 1.03 in log file

### ISSUE THREAD

**Issue by flecoufle** [node-red/node-red-docker#172]
### What are the steps to reproduce?

$ docker run nodered/node-red:**1.0.4**-minimal

### What happens?
in log
> ...
>node-red-docker@**1.0.3** start /usr/src/node-red
...

### What do you expect to happen?
Node-RED version: v1.0.4

### Please tell us about your environment:

[ ] Platform/OS: GCP
[ ] Browser: Chrome
    
    $ docker inspect xxx | grep VERSION
    "NODE_RED_VERSION=v1.0.3",
injected env var need to be bumped

**Comment by knolleary** [comment]
Please use the latest: `nodered/node-red:1.0.4-2-minimal`

I screwed up the publish of 1.0.4 - need to tidy up the references in the readme.

**Comment by knolleary** [comment]
I have deleted the images tagged with 1.0.4 and they are being rebuilt at the moment.

For now you can use `nodered/node-red:1.0.4-2-minimal`

**Comment by flecoufle** [comment]
OK - Thanks
