### ISSUE TITLE
Potentially breaking changes in 1.0.4 release

### ISSUE THREAD

**Issue by beevelop** [node-red/node-red-docker#173]
### What are the steps to reproduce?
Build you own "subimage" of `nodered/node-red` and customize the execution to use a different path for your `settings.js` file.
```Dockerfile
FROM nodered/node-red:1.0.4

LABEL traefik.enable="true"
LABEL traefik.docker.network="traefik"
LABEL traefik.port="1880"

RUN mkdir /neo

COPY package.json red.js settings.js /neo/

[...]

# Which executes: node $NODE_OPTIONS red.js $FLOWS --userDir /data --settings /neo/settings.js
ENTRYPOINT ["npm", "start"]
```

### What happens?
The image still works seemingly flawless, but in combination with the loadbalancer Traefik no requests will be forwarded to the container. This is due to the new **healthchecks**. They require the `settings.js` to be placed at `/data/settings.js`. But placing the `settings.js` into `/data` is not an option, if you bind this folder to a volume and still want to update the contents of `settings.js` regularly through your CI / CD pipeline.

Running the healthchecks manually results in the following exception:
```
bash-5.0$ node /healthcheck.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/data/settings.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    [...]
```

### What do you expect to happen?
The `settings.js` referenced in the healthchecks should be dynamic or at least configurable through an ENV imho.

### Please tell us about your environment:
- Image: `nodered/node-red:1.0.4`

**Comment by dceejay** [comment]
Not quite sure why this should break - the internal /data directory is where Node-RED expects to find any extra nodes, setting and indeed the flow file. If you mount an external volume to save them that should still be visible as /data internally.

**Comment by beevelop** [comment]
Yes, by default the `settings.js` is located at `/data`. But if you make use of the `--settings` command line argument, you can place the settings anywhere. Unfortunately the path in the healthcheck itself is hard-coded, so it does not respect the `--settings` argument passed to the `CMD`.

**Comment by dceejay** [comment]
Can you use `--no-healthcheck ` as part of run command to disable it ?

**Comment by dceejay** [comment]
Have added notes about disabling  Healthcheck to README
