### ISSUE TITLE
Deprecation warnings from request and mkdirp

### ISSUE THREAD

**Issue by MiLaak** [node-red/node-red-docker#176]
Building custom node-red-docker with `docker-make.sh` gives following deprecation warnings:

```npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142```

```npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)```

I'm running the build script in Google Cloud Shell. Not tested in other environments. Is the warning because of the environment used or is it because of node red or node red docker?

**Comment by knolleary** [comment]
Yes, they are deprecated modules used by Node-RED.

**Comment by knolleary** [comment]
Just to clarify - `request` is a module we depend on directly and we have a chore in the backlog to migrate off it.

`mkdirp` is a few levels deep down the tree of dependencies and not one we can remove directly until the modules between us and them update.

**Comment by MiLaak** [comment]
Thanks for clarifying. I have one further question since I'm not too familiar yet with docker and npm etc. Regarding to `mkdirp` is it used during building the docker image or does node-red use it on runtime. I'm just concerned if it is used runtime and if there are any security concerns.

**Comment by knolleary** [comment]
As I said, `mkdirp` is a dependency a few levels deep of a module that Node-RED does use. I cannot say if Node-RED causes the mkdirp code to be exercised or not.

But given this is a deprecation and not a security warning then I suspect the risk is exceedingly low - especially if you aren't running untrusted code yourself.
