### ISSUE TITLE
Permissions problem deploying on OpenShift

### ISSUE THREAD

**Issue by hammoaj** [node-red/node-red-docker#179]
### What are the steps to reproduce?
Deploy Node-RED from Dockerfile to OpenShift environment using:
`FROM nodered/node-red`

### What happens?
Error 13 (permissions) when starting container when it tries writing to `/usr/src/node-red` and `/data`. This is because OpenShift containers run as a random UID and with a GID of 0 (root). It's possible to change the GID and permissions of `/usr/src/node-red` in the local Dockerfile, but this doesn't work with `/data` because it is declared as a WORKDIR and any subsequent changes to it are ignored.

### What do you expect to happen?
Would it be possible to set the GID for `/usr/src/node-red` and `/data` to 0 (root) and do a `chmod -R g+rwX` on both `/usr/src/node-red` and `/data` in the standard Dockerfile? This shouldn't impact running this build in a standard Docker container but will enable it to build and run on OpenShift without alterations.

### Please tell us about your environment:

[ ] Platform/OS: Red Hat OpenShift

[ ] Browser: N/A

**Comment by dceejay** [comment]
currently we do
```
    chown -R node-red:node-red /data && \
    chown -R node-red:node-red /usr/src/node-red
```
can you be completely explicit with what you propose instead ? Thanks

**Comment by hammoaj** [comment]
This won't work on Openshift as it runs as `_random-uid_:root`. Could you do this?
```
chown -R node-red:root /data && chmod -R g+rwX /data \ 
chown -R node-red:root /usr/src/node-red && chmod -R g+rwX /usr/src/node
```

**Comment by dceejay** [comment]
OK - i have pushed a set of images to the test repo at dockerhub nodered/node-red-dev
They are vanilla 1.0.6 with your changes above to test.

(I assumed that 2nd lien should have ended -red eg
`chown -R node-red:root /usr/src/node-red && chmod -R g+rwX /usr/src/node-red`

**Comment by hammoaj** [comment]
Indeed - thanks Dave....will try and test over the weekend

**Comment by dceejay** [comment]
Up to you - they are all listed here - https://hub.docker.com/r/nodered/node-red-dev/tags I would start with docker pull nodered/node-red-dev:dev (for node10)  or docker pull nodered/node-red-dev:dev-12 for node12

**Comment by hammoaj** [comment]
There still seems to be a permissions issue with `/usr/src/node-red` but it’s fixed with `/data`, that may not be an issue though. It deploys on Openshift as-is, but **Manage Palette** won’t work. To get that to work I hard to override the `ENTRYPOINT` as follows:
```
ENTRYPOINT ["npm", "start", "--cache", "/data/.npm", "--", "--userDir", "/data"]
```

Could we get that updated in the source Dockerfile? That should mean that we have an image that will deploy on Openshift out of the box.

**Comment by hammoaj** [comment]
Found the issue with `/usr/src/node-red` permissions, line 70 in the Dockerfile is resetting the permissions back, it needs to be changed to:
```
RUN chown -R node-red:root /usr/src/node-red && \
```

**Comment by dceejay** [comment]
Ok - repushed to https://hub.docker.com/r/nodered/node-red-dev/tags

**Comment by hammoaj** [comment]
Permissions issue fixed - thank you. It still needs the ENTRYPOINT line fixing as the npm cache needs changing to somewhere it can write to:
```
ENTRYPOINT ["npm", "start", "--cache", "/data/.npm", "--", "--userDir", "/data"]
```

**Comment by dceejay** [comment]
ok - fixed that also.

**Comment by hammoaj** [comment]
Thanks Dave - all looks good. Can this be promoted to being the standard node-red-docker image?

**Comment by dceejay** [comment]
Ok now being promoted to master. Closing this
