### ISSUE TITLE
Official Ubuntu/Debian Image

### ISSUE THREAD

**Issue by s4ke** [node-red/node-red-docker#183]
Hey,

first of all, thanks for the awesome project that Node-RED is.

Second, would it be possible to have an official Ubuntu/Debian base Node-RED image? I see we can fork this project and manage it ourselves, but it would be awesome to have it on the official Docker Hub.

**Comment by knolleary** [comment]
Hi @s4ke  - as the issue template you've deleted says, we prefer to have feature requests/suggestions raised on the forum, and keep the issue list as just that - issues.

There are countless possible base images we could generate images for - all of which add some maintenance cost in keeping things up to date.

The images are already based on https://hub.docker.com/r/amd64/node/ albeit the `alpine` variant. But you can readily build your own debian based image without forking the project. Use the `--build-arg OS=buster` argument to the `docker build` command - https://github.com/node-red/node-red-docker/blob/master/docker-custom/docker-make.sh#L12 - and you'll get debian buster based images.

**Comment by s4ke** [comment]
Okay, sorry about that, but thanks for the explanation nonetheless.

**Comment by s4ke** [comment]
Just as a fyi: Just changing to `--build-arg OS=buster` was not enough. I ended up forking the project after all: https://github.com/neuroforgede/node-red-docker

**Comment by knolleary** [comment]
Ah good point re apk/apt-get... hmm, we should think about that as it otherwise makes being able to set the `OS` to non-alpine a bit redundant.

**Comment by s4ke** [comment]
I also had to change some package-names as well as the usual contenders like the `adduser` command that does never behave the same across distros.

**Comment by twocolors** [comment]
@knolleary do you have any ideas how to build a container based on debian ?
Now we cannot use the library / binaries from the raspberry host system

**Comment by s4ke** [comment]
@twocolors as an example, please take a look at the repository I linked above. This is for amd64, but should get you started.

**Comment by twocolors** [comment]
@s4ke i see you repository, but want official support.

**Comment by dceejay** [comment]
we are all volunteers here - your support is just as valid as mine.
