### ISSUE TITLE
Password for the node-red user

### ISSUE THREAD

**Issue by seanboc** [node-red/node-red-docker#19]
Hi, When trying to install the Rpi-GPIO python library within the container, it needs access to be able to a sudo within the container. Can you tell me what the 'root'  password is so I can do a sudo from the node-red user. Thanks

S.

**Comment by dceejay** [comment]
We use the default hypriot node4 image that doesn't have a root user (AFAIK) and we don't add the node-red user to the sudoers list... so don't think that will just work.
In the meantime there is an image with gpio enabled - https://hub.docker.com/r/nieleyde/rpi-nodered-gpio/

Happy to entertain the idea of a PR.

**Comment by seanboc** [comment]
Thanks Dceejay for coming back.  I will take a look at the alternate image and give it a try out.

**Comment by kylehadland** [comment]
Hello, I am having a similar issue.  I am trying to access the i2c interface on a RPI and need to add a group 'i2c' to the image.

**Comment by jthomas** [comment]
The GPIO images have now been added to the base image:
https://github.com/node-red/node-red-docker/blob/master/rpi/Dockerfile

I'm closing this ticket as it's not valid anymore.
