### ISSUE TITLE
Host key verification failed when using Projects and GIT

### ISSUE THREAD

**Issue by mmick08** [node-red/node-red-docker#191]
### What happens?

after container restart we are getting "Host key verification failed. - The repository host key could not be verified. Please update your known_hosts file and try again." Error when trying to push/pull git.
it seems that it is necessary to maintain known_hosts file but that's not possible in openshift/docker environment. 
As sometimes the GIT Repository is also hosted by a company within the intranet different host-keys are involved (f.e. load balancing)

Therefore it should be possible to set either **StrictHostKeyChecking no** somewhere in the Container Environment or accept adding the new host-key via GUI cause it seems this process takes place only during initial GIT configuration.

### What do you expect to happen?

it should be possible to use GIT Integration within projects without getting any "Host key verification failed" errors.

### Please tell us about your environment:

FYI: i did a temporary fix by adding the following into my Dockerfile
RUN echo "Host *" >> /etc/ssh/ssh_config
RUN echo "	StrictHostKeyChecking no" >> /etc/ssh/ssh_config

- [ ] Node-RED version: v1.1.0 (latest container image)
- [ ] Node.js version: 
- [ ] npm version: 6.14.4 (latest container image)
- [ ] Platform/OS: official container image hosted on openshift platform
- [ ] Browser: Edge Chromium

**Comment by hardillb** [comment]
I still think your point about host keys still isn't valid. They should match across all load balanced machines or they should all be imported upfront. A changing host key is a sign of a man in the middle attack and should be treated as such, disabling the check is not the right default approach.

This containers default of checking host keys is correct for most users, if you want to disable that then build your own container (by extending the official one) and adding the commands you mentioned. Or mount your own version of /etc/ssh/ssh_config into the container.

**Comment by mmick08** [comment]
its not about the **StrictHostKeyChecking no** in this case. this was just an idea how to fix it in a local environment. in my case the host key has not changed it just seems to me that the known_host file is not stored on a persistent basis.

it is basically the same issue than this one: https://github.com/node-red/node-red/issues/1647
and the reporter got it right in my opinion:

1. enter docker container command line with docker exec ...
2. change to /data/red/projects/<git-repo>
3. execute git push origin master
4. Accept host key with yes **<------------- guess here is the problem**"

**Comment by hardillb** [comment]
OK, That is a different problem to the you described in your proposed solution.

The right answer is probably to move the `known_hosts` file to under `/data` which I think you can do in the /etc/ssh_conf file with the `UserKnownHostsFile` option. That way the file should be persisted to the same volume as the flows. The tricky bit might be getting the path permisions right.

**Comment by mmick08** [comment]
Thanks for your help. But if that is the case and solves the issue it would be the best solution to introduce a new env variable like `UserKnownHostsFile=<yourlocation>`. Do you think thats possible for future builds ?

**Comment by natcl** [comment]
I'm curious about this too as I've been wanting to build a Docker image that is project ready and this issue blocks it.
In my case I would be happy with a way to forward the GIT_SSH_COMMAND env var too... in this case I could specify to not check for the host key but I also like the idea of redirecting the known hosts files elsewhere as it's a bit more secure.

**Comment by hardillb** [comment]
@natcl You can also pass the `UserKnownHostsFile` option direct to ssh with that env var to put the `knownhosts` somewhere persistent

**Comment by hardillb** [comment]
In fact the `GIT_SSH_COMMAND` is the right way to do this rather than adding a new env var that might clash.

**Comment by natcl** [comment]
The only problem now is that the GIT_SSH_COMMAND is not passed from docker to the actual runtime but I think if it was it could probably solve several issues.

**Comment by knolleary** [comment]
We already use GIT_SSH_COMMAND in order to pass the right ssh key in - https://github.com/node-red/node-red/blob/98c736492403dc8e2af7eda5d419e421d6183ea6/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/projects/git/index.js#L109

But having some way of setting additional flags would be worth looking at.

**Comment by mmick08** [comment]
as i think many users will have the same problem its may be worth thinking about passing through the GIT_SSH_COMMAND env var ?!

**Comment by knolleary** [comment]
As I said in my reply, we already use GIT_SSH_COMMAND to get things to work at all. Yes we need some way to pass through extra options, but it won't be via GIT_SSH_COMMAND directly.

**Comment by abhishek063** [comment]
+1. I stumbled upon the same issue.

**Comment by billimek** [comment]
Another project deals with this issue via a shell script with their dockerfile build.  It may be worth exploring for hints for a long-term solution for this problem: https://github.com/fluxcd/flux/blob/master/docker/known_hosts.sh

**Comment by jbperrin88** [comment]
:+1:

**Comment by CTGControls** [comment]
I think we are having this same problem. Every time I restart the container I can not comment to my remote repository. I get the error:

**Comment by knolleary** [comment]
> Another project deals with this issue via a shell script with their dockerfile build. It may be worth exploring for hints for a long-term solution for this problem: https://github.com/fluxcd/flux/blob/master/docker/known_hosts.sh

Having looked at how they use this, I think it would make a lot of sense for us to take a similar approach and pre-populate known_hosts in a similar fashion as part of our build.

**Comment by hardillb** [comment]
I've included the script from flux (it's under Apache-2.0 license) in a pull request targeted at the 2.0 beta. 
I've used their list to start with, but do we know of any others we might want to add?

 - Github (github.com)
 - Gitlab (gitlab.com)
 - Azure (ssh.dev.azure.com)
 - Visual Studio (vs-ssh.visualstudio.com)
 - BitBucket (bitbucket.org)
 - Google (source.developers.google.com port 2022)

I've also included instructions in the README for how to generate your own for internal/private git servers and mount it into the container

**Comment by dceejay** [comment]
so this will "get fixed" if we merge that to master in main project ?

**Comment by hardillb** [comment]
Yep, should be able to close this off.

**Comment by peter-vanpoucke** [comment]
Will this fix also keep my custom hosts in their?

**Comment by hardillb** [comment]
This will populate the `/etc/ssh/ssh_known_hosts` file as an early step in the build of the `nodered/node-red` container.

If you extend the container and overwrite that file then it will use your version. Or if you mount a version of the file over the existing one when you start the container it will use the newly mounted version.

The plan is to include this in the images for the v2.0 beta so people can test before push it to the `nodered/node-red:latest` tag

**Comment by hardillb** [comment]
This should be in the v2.0.0-beta.2 release so available to test

**Comment by rob-mccann** [comment]
@hardillb fyi - I'm still getting this issue on 2.0.3

**Comment by sumnerboy12** [comment]
I have this working on v2.0.3 with a local instance of Gitea.

I am running Node RED using Docker so had to mount a volume inside my container pointing to a file with the output of;
```
ssh-keyscan -t rsa git.mydomain.com
```

Something like this;
```
    volumes:
        /data/gitea_known_hosts:/etc/ssh/ssh_known_hosts
```

Then I added an SSH key in Node RED and copied the public key to Gitea, and finally added a git remote via Project Settings with the URL (i.e. no `ssh://` prefix or `.git` suffix);

```
git@git.mydomain.com:ben/nodered-repo
```

Then it started working,

**Comment by hardillb** [comment]
It looks like this didn't get merged before the 2.0,x release. I'll fix it in the morning and make sure it's there for 2.0.4

**Comment by sumnerboy12** [comment]
Weird, I was having all sorts of problems before v2 and now it is working. Dumb luck?!

**Comment by hardillb** [comment]
Closing this now as it should be good from 2.0.4

**Comment by penguineer** [comment]
As an alternative you can mount `{{ nodered_data }}/known_hosts:/usr/src/node-red/.ssh/known_hosts` and make sure that `known_hosts` exists as a file with mode `0600` and ownership `1001:0` at the host location before the container starts (otherwise docker creates a directory).

You will still need to put your host key there, but and changes from the internal SSH are now persistent.

**Comment by zba** [comment]
> Closing this now as it should be good from 2.0.4

so how to update known hosts from GUI ?

**Comment by thomasvnl** [comment]
> Closing this now as it should be good from 2.0.4

I just ran into this issue, trying to use my own server as "known_host", with projects and NodeRED:4.0.5 running as docker container. I did search documentation but could not find anything helpful and ended up doing the same as OP and entered the container to manually add the host to this known_hosts file. Would have been nice to be able to do this from the NodeRED UI directly instead.

**Comment by rohitashav-goLang** [comment]
I have a question, we are doing the same process here, we have a known_hosts file, and it mounted to hosts with proper permissions. but we can see that it's still giving the known_hosts versification error, I am pity sure I am making some mistake here. can someone pls help here? in logs I can see its trying to access config file, but I have notice (inside and outside the container) that the config file not been created anywhere. and yet it works before restart but not after restart. 

9 Jul 11:53:19 - [debug] git -c credential.helper= push origin HEAD:main --porcelain

9 Jul 11:53:19 - [debug] [err] Can't open user config file /home/node-red/.ssh/config: No such file or directory

9 Jul 11:53:19 - [debug] [err] fatal: Could not read from remote repository.

9 Jul 11:53:19 - [debug] [err]

9 Jul 11:53:19 - [debug] [err] Please make sure you have the correct access rights

9 Jul 11:53:19 - [debug] [err] and the repository exists.

9 Jul 11:53:19 - [debug] rc=128

docker-compose : version: "2.4"

services:
  nodered:
    image: nodered/node-red:0.49.1
    ports:
      - "1880:1880"
    mem_limit: 450mb
    network_mode: bridge
    restart: always
    user: root:node-red
    volumes:
      - ./home/edge/node/node-red:/home/nodered/node-red-home
      - ./home/edge/data/node-red/.ssh/:/home/nodered/node-red/.ssh/

**Comment by hardillb** [comment]
@rohitashav-goLang Please do not ask questions on long closed issues.

I will offer 2 points

1. There is no `nodered/node-red:0.49.1` container
2. The user in the containers home directory is in `/usr/src/node-red`  there should be nothing in `/home/nodered` 

This heavily implies you are building your own container and not using the ones built by the Node-RED project,
