### ISSUE TITLE
[request to ammend install guide] "node-red admin" command access for Docker installations

### ISSUE THREAD

**Issue by MaxVRAM** [node-red/node-red-docker#193]
## Background

In the documentation page [securing Node-RED](https://nodered.org/docs/user-guide/runtime/securing-node-red#generating-the-password-hash), it explains how to secure the installation by using the command `node-red admin hash-pw` that generates a hash to attach to a user in the settings file under `adminAuth`.

## Issue

When using the Docker installation of Note-RED, `node-red` is not installed as a terminal command on the host.

## Solution

Thankfully, the ~~moderator~~ (oh, ahem) creator @knolleary was able to reply to my request for help in the [Node-RED forum topic](https://discourse.nodered.org/t/using-command-line-access-with-the-docker-install/30434) I posted, with a wonderfully concise and accurate solution:

> good question - the docker container doesn't put the node-red command on its path.<br>
> But you can do this:
> ```bash
> docker exec -it node-red npx node-red admin hash-pw
> ```
> `npx` is a command provided by `npm` that can be used to run any npm-installed executable in the local directory.

## Suggestion

If it fits within the documentation format/ethos, it would be great to have this information within the documentation so that other people choosing a Docker install can find this information easily. Perhaps the [getting started Docker](https://nodered.org/docs/getting-started/docker) page would be a good place to add it for reference.

**Comment by MaxVRAM** [comment]
Solved with the merged commit

**Comment by grahamPegNetwork** [comment]
@MaxVRAM 
While I realize it is more a matter of docker/compose, the docker commands listed don't directly translate for people using docker-compose. Could we get a compose version in the documentation as well?

I can probably get it figured out, but it requires I research the differences between docker and docker-compose. Sure it's something I should know how to do, but I'm just trying to set a password, this should be quick and simple.
