### ISSUE TITLE
Default version of node.js for :latest

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red-docker#199]
The current default version of node js (when you pull :latest) is v10.

The intention is to only jump this forwards on major releases of Node-RED.
the current Roadmap is here https://nodered.org/about/releases/ - though there is a small possibility that we may need to bring 2.0 earlier in order to tidy up some library dependencies that require security patches (that don't affect Node-RED) - but drop node 8 support. 

If we do do v2 this year the proposal would be to make node12 the default docker image, add node 14 and drop node 10.
If we do it next year (or indeed for  Node-RED v3) in that timeframe we would make node 14 the default, leave node12, and drop node 10.

**Comment by hardillb** [comment]
As part of the GH actions work I picked NodeJS 14 as the default for latest because I didn't see this issue. Now it's shipped we can't really roll it back to 12 as it will break existing users with native nodes installed. I will check all the doc is consistent with this outcome.

**Comment by dceejay** [comment]
actually I agree - 14 as default makes more sense tbh.
