### ISSUE TITLE
0.16 core serialport removed but cannot add back in

### ISSUE THREAD

**Issue by spants** [node-red/node-red-docker#21]
I'm using Volumes for /data.  Adding the node-red-node-serialport via the Manage Palette doesn't work - they dont appear in the palette. I will post logs if required....

**Comment by spants** [comment]
will try alternate install and reopen if necessary

**Comment by spants** [comment]
I have tried using Node-RED Admin tool and Container Shell methods to add serial port but these do not work (is it because of permissions?) - they seem to install but do not show in the palette. The only way I could use it is to create my own Dockerfile shown under the "Building Custom image".

Could serialport be loaded by default just for Docker images?

**Comment by jthomas** [comment]
Hello, can you provide the following details to help me try and replicate the bug..... 

- What host are you running this from?
- What image tag are you using?
- Can you paste the logs from Node-RED startup and during the install process?

**Comment by jthomas** [comment]
Is there any update on this? Otherwise, I'll close it.
