### ISSUE TITLE
Docker latest tag seams to be 1.2.5 not 1.2.6 is this right?

### ISSUE THREAD

**Issue by AleksCee** [node-red/node-red-docker#213]
Hello,

in the last 24h many new tags for the 1.2.6 release has been published but the last tag seams to be 1.2.5, is the right, or is there some issue by the build?

Thanks, Alex

**Comment by knolleary** [comment]
Yes, we're having issues with the build.

**Comment by AleksCee** [comment]
Cool, thank you for the quick reply. Then i will be patient. And thanks for the excellent work - I really love nodeRED!!!!

**Comment by AleksCee** [comment]
Docker for 1.2.6 is online - thanks
