### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Erik262** [node-red/node-red-docker#215]
### What are the steps to reproduce?
pull node-red-docker from portainer and run the container

### What happens?
directly after starting the container this message appears:
`EACCES: permission denied, copyfile '/usr/src/node-red/node_modules/node-red/settings.js' -> '/data/settings.js'`

### What do you expect to happen?
A working node-red-docker container :) 

### Please tell us about your environment:

[ ] Platform/OS:
Synology NAS

[ ] Browser:
 
  - If you are a Portainer user, please attach a screenshot of your container details.
  
![Screenshot 2021-01-18 at 11 53 59](https://user-images.githubusercontent.com/11977647/104906450-0044dc00-5984-11eb-8f53-9ee1b5bf2d10.png)

I also added a volume:
/volume/docker/NodeRED/data : /data

**Comment by dceejay** [comment]
Do these threads help at all ? https://discourse.nodered.org/search?q=synology%20permissions
(We don't have a Synology to test against so will be up to the community to fix.)

**Comment by Erik262** [comment]
@dceejay THANK YOU I found the solution in one of these threads from your link!
To solve this problem just change the username "node-red" to "root" that's all :)

![Screenshot 2021-01-18 at 13 02 05](https://user-images.githubusercontent.com/11977647/104913247-9af5e880-598d-11eb-8636-8a398495f981.png)
