### ISSUE TITLE
executor failed during creation of node red doker

### ISSUE THREAD

**Issue by EnricoBeltramo** [node-red/node-red-docker#216]
### What are the steps to reproduce?
Try to install docker custom alpine 

### What happens?
When I try to create tag of custom docker with follow command (copied from .sh file):
docker build --rm --no-cache --build-arg ARCH=amd64 --build-arg NODE_VERSION=12 --build-arg NODE_RED_VERSION=1.2.7 --build-arg OS=alpine --build-arg BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")" --build-arg TAG_SUFFIX=default --file Dockerfile.custom --tag testing:node-red-build .
I tried same command in wsl2, with same result

 I have follow error:
executor failed running [/bin/sh -c apk add --no-cache --virtual buildtools build-base linux-headers udev python &&     npm install --unsafe-perm --no-update-notifier --no-fund --only=production &&     /tmp/remove_native_gpio.sh &&     cp -R node_modules prod_node_modules]: exit code: 127

### What do you expect to happen?
Creation of docker tag correctly compiled

### Please tell us about your environment:

[ ] Platform/OS:
Win10

[ ] Browser:
Chrome
 
  - If you are a Portainer user, please attach a screenshot of your container details.
  
    ```
    Containers -> Click on the node-red container -> Scroll to Container Details and take a screenshot
    ```
    
  - If you are a command line user please execute the following command and attach the log file.

    ```shell
    docker inspect <container_id> > container.log
    ``` NA: docker not created

**Comment by dceejay** [comment]
well something in that line is not installing  - so causing the build to fail - you could try splitting that into multiple apk add lines and mov the && parts to other lines so try to isolate the error.  I'm not sure alpine will support gpio though so maybe it is that

**Comment by travis-icorein** [comment]
I was having a very similar (same?) issue.

The final error that I was receiving was that the file ` /tmp/remove_native_gpio.sh` could not be found.  Commenting out the [affected line](https://github.com/node-red/node-red-docker/blob/master/docker-custom/Dockerfile.custom#L43) and everything after, and it would then build.  Inspecting the resulting image, and the file was in fact where it was supposed to be (with the correct permissions).

I finally did a fresh clone in WSL (had used PowerShell previously), and it would then fully build without issue.  I did notice I got another error initially the first time around too (when cloned via PowerShell) when executing the [build script](https://github.com/node-red/node-red-docker/blob/master/docker-custom/docker-alpine.sh#L1) which showed unexpected characters after the first line.  Converting the script from CRLF to LF (windows to nix, via VS Code) resolved that problem.

I suspect it is a line termination issue.

**Comment by dceejay** [comment]
Happy to look at a PR so we can see your changes if you like. Thanks

**Comment by travis-icorein** [comment]
I don't know that anything further is required/needed (seems to be "user-error")

**Comment by dceejay** [comment]
so ok to close this issue then ?

**Comment by travis-icorein** [comment]
That would be my .02, but I didnt create the ticket/issue. @EnricoBeltramo ?

**Comment by dceejay** [comment]
no further response - closing.
