### ISSUE TITLE
ssl root certs missing

### ISSUE THREAD

**Issue by tve** [node-red/node-red-docker#223]
### What are the steps to reproduce?

- launch container
- do a docker exec to get a shell in the container
- curl https://favqs.com/api/qotd

alternatively:
- create an https request node and make it fetch the above url

### What happens?
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
alternatively, the http request node outputs
```
"Error: unable to verify the first certificate : https://favqs.com/api/qotd"
```

### What do you expect to happen?

I expect the SSL root certs to be populated in the image so I can connect to HTTPS sites.

### Please tell us about your environment:

[ ] Platform/OS:

armv7, running node-red image 1.2.9

**Comment by dceejay** [comment]
noted

**Comment by tve** [comment]
As far as I can tell, what's missing is `apk install ca-certificates`, at least that does the trick for me.

**Comment by dceejay** [comment]
yup exactly - have added to my local version

**Comment by dceejay** [comment]
have added to main build script in master so should be in 1.3 as and when.
