### ISSUE TITLE
healthcheck.js is expecting "settings.js" in folder /data

### ISSUE THREAD

**Issue by janvda** [node-red/node-red-docker#232]
I am using a different userDir than `/data/` for deploying my flows and settings files.

FYI here the relevant extract from my Dockerfile:

```
FROM nodered/node-red:1.2.9-12
...
COPY package.json /flows/
# The following command will build all the nodes specified in the package.json that is copied
# in previous command.
RUN  cd /flows ; npm install --unsafe-perm --no-update-notifier --no-fund --only=production

# Copy Node-RED flow files and settings to userDir
COPY  flows.json flows_cred.json settings.js /flows/

# start Node-RED
ENTRYPOINT  npm start -- --userDir /flows
```

Everything works fine except that portainer is reporting my container as unhealthy:

![image](https://user-images.githubusercontent.com/17238398/117534676-cced9200-aff2-11eb-8661-5acc89aef409.png)

FYI The following is reported in the container health section of portainer for that container:

```
internal/modules/cjs/loader.js:818 throw err; 
Error: Cannot find module '/data/settings.js' Require stack: - /healthcheck.js 
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) 
at Function.Module._load (internal/modules/cjs/loader.js:667:27) 
at Module.require (internal/modules/cjs/loader.js:887:19) 
at require (internal/modules/cjs/helpers.js:74:18) 
at Object.<anonymous> (/healthcheck.js:3:16) 
at Module._compile (internal/modules/cjs/loader.js:999:30) 
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) 
at Module.load (internal/modules/cjs/loader.js:863:32) 
at Function.Module._load (internal/modules/cjs/loader.js:708:14) 
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) 
{ code: 'MODULE_NOT_FOUND', requireStack: [ '/healthcheck.js' ] }
```

**Comment by janvda** [comment]
This is the same issue as reported in following forum topic:
* https://discourse.nodered.org/t/node-red-docker-settings-js/26529

The following **work around** fixed the issue for me =
* _copy the settings.js also to folder /data_

In other words I have added following line to my Dockerfile.
```
...
COPY settings.js /data/
...
```

**Comment by janvda** [comment]
As solution it would be good that it doesn't hard code the location of `settings.js` in [healtcheck.js](https://github.com/node-red/node-red-docker/blob/master/.docker/healthcheck.js) program

**Comment by knolleary** [comment]
That is only half the solution. The question that needs answering is how does healthcheck.js (which runs independently of Node-RED) know what settings file you have configured Node-RED to use.

**Comment by janvda** [comment]
@knolleary , I see your point.  I also went through the [readme](https://github.com/node-red/node-red-docker#readme) and I see that this repository assumes that the settings and flows are stored under `/data/` folder.  

So setting `--userDir` to something different than `/data` is not really supported by this repository.
I can live with that.
So for me it is fine to close this issue !

**Comment by dceejay** [comment]
Also you can add `--no-healthcheck` to the run command to turn off the healthcheck.
But yeah - while "I" think it's useful it does seem to cause more trouble than it's worth tbh. Maybe it's something to leave out of the base and let people who want it to add as part of their build.

**Comment by janvda** [comment]
@dceejay , thanks for sharing the --no-healthcheck option.  
I have adapted my dockerfile so that it is using `/data` folder for my flows, package.json and settings.
This was a very small change.

Indeed trying to fix this might cause more trouble than trying to fix it.
So I am closing it as it is working per design (= flows and settings are expected to be stored under `/data` folder).
