### ISSUE TITLE
Latest still using node 4.x on docker hub

### ISSUE THREAD

**Issue by sputnick** [node-red/node-red-docker#24]
Hey didn't the node 6.x update in the DockerFiles make it to docker hub? Seemed to have been updated at the same time as node-red update but I'm always getting node 4.x with the slim version.

**Comment by jthomas** [comment]
I've pulled the `slim` tag down and started a container and it is using the latest version of Node.js.

```
[09:29:29 ~/]$ docker run -it -p 1880:1880 nodered/node-red-docker:slim
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.9.4
npm info lifecycle node-red-docker@0.16.2~prestart: node-red-docker@0.16.2
npm info lifecycle node-red-docker@0.16.2~start: node-red-docker@0.16.2
```

How are you running the container? Can you verify you've definitely pulled down the latest version?

**Comment by sputnick** [comment]
Ugh you are right - I was getting a cached version. However this line in package.json still says node v4.x.x though.

https://github.com/node-red/node-red-docker/blob/master/package.json#L34

**Comment by jthomas** [comment]
Ignore that line - it doesn't affect the build :) 

Glad this was easily resolved!
