### ISSUE TITLE
Non-existing path as value for 'main' in package.json

### ISSUE THREAD

**Issue by trandhbao** [node-red/node-red-docker#243]
### What are the steps to reproduce?
cat package.json

### What happens?
...
"main": "node_modules/node-red/red/red.js",
...

### What do you expect to happen?
...
"main": "node_modules/node-red/red.js",
...

### Please tell us about your environment:
[ ] Platform/OS:
Ubuntu 20.04.2 LTS
[ ] Browser:
 Chrome

**Comment by knolleary** [comment]
Well spotted. Given this is not an npm module, there should not be a `main` entry at all. Similarly we should add `"private": true` to make it clear this isn't to be published to npm.

**Comment by trandhbao** [comment]
Thanks.

**Comment by hardillb** [comment]
We'll close this when it gets merged
