### ISSUE TITLE
linux/arm64/v8 Support

### ISSUE THREAD

**Issue by rushsteve1** [node-red/node-red-docker#250]
The `latest` Docker tag does not support the `linux/arm64/v8` architecture aka `aarch64`. There are the separate `-arm64v8` tags, but they are out of date.

This was split from #248 

### What are the steps to reproduce?
Try to pull and run the `latest` Docker image on an `aarch64` machine as per the instructions in the documentation on the Node-RED website.

### What happens?
It pulls the `X86_64` version instead and fails with the following error:
```
standard_init_linux.go:219: exec user process caused: exec format error
```

### What do you expect to happen?
A `linux/arm64/v8` image should be pulled.

### Please tell us about your environment:

This is an `aarch64` VM running Oracle Linux 8 (based on RHEL 8) and Podman 3

**Comment by hardillb** [comment]
Can you delete the local copy of the image and pull it again just to be sure you have the latest please (we respan those builds with the same tag name about the time you added the comment to the other issue).

**Comment by rushsteve1** [comment]
Oh, yes that seemed to fix it, odd. Is the `arm64` Docker label the same as `aarch64`? Technically `aarch64` is a form of ARM v8, so I assumed the issue had to do with that.

**Comment by hardillb** [comment]
Yes, they are the same as far as I can tell.

I'm going to close this as you have a running build now.

**Comment by rushsteve1** [comment]
Yes, thank you @hardillb!
