### ISSUE TITLE
Broken link on the README documentation to build custom docker images

### ISSUE THREAD

**Issue by antoine-em** [node-red/node-red-docker#255]
On the `README.md` located here https://github.com/node-red/node-red-docker/tree/master/docker-custom

In this section the link is broken

> 5. Advanced Configuration
> The relevant Dockerfile can be modified as required. Examples of how to extend Dockerfiles to add prerequisite libraries can be found here.

https://nodered.org/docs/getting-started/docker-custom -> Error 404

**Comment by hardillb** [comment]
Yep, just needs the docs page [merging](https://github.com/node-red/node-red.github.io/pull/226), on it.

**Comment by hardillb** [comment]
Try node please

**Comment by hardillb** [comment]
closed via https://github.com/node-red/node-red.github.io/pull/226
