### ISSUE TITLE
Is there any way to remove unused node-red modules?

### ISSUE THREAD

**Issue by sputnick** [node-red/node-red-docker#26]
I'm trying to slim down a docker container for a flow that only uses http and websockets and some custom functions.

**Comment by knolleary** [comment]
Beyond the core nodes which are included with Node-RED, this image includes for other, nondefault, but useful node modules, as listed here: https://github.com/node-red/node-red-docker/blob/master/package.json

You could rebuild the image with a modified package.json that doesn't include those four.
If you wanted to strip out any of the core nodes, you'd need to include a step in your docker build after the npm install step that manually rm's the nodes you don't want from under the module's nodes directory.
