### ISSUE TITLE
v1.3.6: Step 8/27 : COPY .docker/known_hosts.sh . COPY failed: file not found in build context or excluded by .dockerignore: stat .docker/known_hosts.sh: file does not exist

### ISSUE THREAD

**Issue by schildbach** [node-red/node-red-docker#263]
### What are the steps to reproduce?

```
$ git status
HEAD detached at v1.3.6
nothing to commit, working tree clean
```

Run `./docker-debian.sh`.

### What happens?

```
[...]
Step 8/27 : COPY .docker/known_hosts.sh .
COPY failed: file not found in build context or excluded by .dockerignore: stat .docker/known_hosts.sh: file does not exist
```

### What do you expect to happen?

A successful build.

### Please tell us about your environment:

[ ] Platform/OS:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

$ docker --version
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.3

```

**Comment by hardillb** [comment]
When opening an issue please actually list the steps you ran to get the error. I can guess that you have tried to build the custom containers, but it helps if you are explicit.

Remove the `.docker/` from that line and it will use the local version. I'll fix `Dockerfile.custom` and Dockerfile.alpine`

**Comment by hardillb** [comment]
Fix pushed, pull from head of v1.x branch for changes. I won't be re-tagging v1.3.6 at this point.

**Comment by schildbach** [comment]
Maybe release a v1.3.7?

**Comment by hardillb** [comment]
Not without any changes to the core Node-RED project

**Comment by knolleary** [comment]
It would be `v1.3.6-2` if anything. But given this isn't a change to the published images, not sure there's a huge merit to publishing new images.

**Comment by schildbach** [comment]
`-2` would be fine to me.

**Comment by hardillb** [comment]
OK, a `v1.3.6-2` has been tagged

**Comment by schildbach** [comment]
Thanks! Building the image works now works for me.
