### ISSUE TITLE
bee22193

### ISSUE THREAD

**Issue by kittophan** [node-red/node-red-docker#266]
### Please tell us about your environment:

[ ] Platform/OS:

[ ] Browser:
 
  - If you are a Portainer user, please attach a screenshot of your container details.
  
    ```
    Containers -> Click on the node-red container -> Scroll to Container Details and take a screenshot
    ```
    
  - If you are a command line user please execute the following command and attach the log file.

    ```shell
    docker inspect <container_id> > container.log
    ```

**Comment by hardillb** [comment]
This is just an empty template, I'll close the issue in 10mins is not edited to complete the template
