### ISSUE TITLE
context & flow variables not visible in subflows

### ISSUE THREAD

**Issue by robiebab** [node-red/node-red-docker#267]
### What are the steps to reproduce?

Create a subflow->-> go inside the subflow-> Create a function node and set an flow and context variable ->Run the node to set the variables-> Go to Context data (to show all variables: context, flow and global variables) -> refresh flow (no data)-> click on the function node and refresh context data (no data)

### What happens?
i can't see the Context and flows beeing set variables 
### What do you expect to happen?
i would except that i could see context and flow variables in Context data

### Please tell us about your environment:

[ ] Platform/OS:
Raspberry Pi -> Docker

docker run -d --network IOT --ip 172.18.0.102 -p 1880:1880  -e TZ=Europe/Amsterdam --no-healthcheck -v Node-Red-Data:/data -v SWAG:/SWAG/ -u root --group-add=dialout --name Node-Red --restart=always nodered/node-red:latest-14

[ ] Browser:
Safari

**Comment by knolleary** [comment]
This repo is for the docker container of Node-RED. It isn't for issues with the core of Node-RED.

In this instance, it is a known limitation that the context sidebar doesn't display context for inside a subflow.

The reasons for this and further discussion is in the forum - can't immediately find the link, but a search for sidebar context should find it.
