### ISSUE TITLE
Consider pushing container images to Github Container Registry (GHCR)

### ISSUE THREAD

**Issue by onedr0p** [node-red/node-red-docker#268]
Hello,

In order to combat dockerhub's imposed rate limits it would be great to host these images on ghcr as well as dockerhub. It should be a minimal change to push the images to ghcr as it's supported across all GitHub repositories for free.

Thanks!

**Comment by hardillb** [comment]
Still waiting to hear back from Docker about getting the restrictions lifted as an OSS project.

**Comment by onedr0p** [comment]
@hardillb Traefik has been trying to get into that program for awhile, I don't know if it is a failure on their end or that Dockerhub is taking a very long time to approve people. My guess they are not very responsive and it will take a very long time (if ever) to get added to that.

**Comment by onedr0p** [comment]
Any update @hardillb ? Would it just be easier to push the images to GHCR as well as dockerhub?

**Comment by hardillb** [comment]
There are no limits on the docker hub images any more, so we are not going to push to multiple repos

**Comment by christaikobo** [comment]
Docker has now implemented a rate limit for anonymous user at 10/hour, which is outrageously low.

Is it possible to reconsider the idea to push to ghcr.io?

**Comment by onedr0p** [comment]
I don't even see that node-red is part of their OSS program anymore. https://hub.docker.com/r/nodered/node-red

I would really love it if they reconsidered publishing to ghcr.

**Comment by hardillb** [comment]
Docker OSS should be back in about a week. They cancelled it with out ever sending the renewal and it got re-enrolled on the 20th, but emails says up to 3 weeks.

I'll look at what can be done for pushing to other repos late.

**Comment by onedr0p** [comment]
> I'll look at what can be done for pushing to other repos late.

Thanks, that would be great. DockerHub is clearly trying to reach peak enshitification levels by treating the community that built up its popularity like parasites now.

**Comment by hardillb** [comment]
Docker Open Source Sponsorship has been re-enabled on the Node-RED repo, but I'll still look to get PR #478 merged for the next NR release
