### ISSUE TITLE
Node-RED Admin Tool installation.

### ISSUE THREAD

**Issue by alexsahka** [node-red/node-red-docker#27]
Hi, 
When trying to install the Admin Tool (npm install -g node-red-admin) root required, but sudo is not working.
Can you tell me please, what Im doing wrong.

**Comment by jthomas** [comment]
Hello @alexsahka 

What will you be using the admin tool for? Node-RED now supports installing nodes through the new palette manager in the UI which means people often don't need to use the admin tool anymore.
https://nodered.org/docs/getting-started/adding-nodes

Also, you can install the admin tool locally and use the `target` command to connect to the Node-RED instance running in Docker.

Does that help?

**Comment by alexsahka** [comment]
I thought this admin tool is to secure web page/login in-to node-red web page/interface.
https://nodered.org/docs/security

**Comment by knolleary** [comment]
node-red-admin does provide a convenience function to hash your chosen password. You don't have to use it; a few lines later the docs you link to show the appropriate node.js command to run that does the same thing.

In both cases, it is just a function to give you an appropriately hashed version of your chosen password, which you then copy into your settings file. It doesn't matter where you run the command (although as the raw node command requires the bcryptjs npm module to be installed, it is convenient to run it in the Node-RED install directory where we know that module will already be)

**Comment by alexsahka** [comment]
Thanks for helping newbie.

**Comment by NicksonYap** [comment]
Just as a note:
`node -e "console.log(require('bcryptjs').hashSync(process.argv[1], 8));" your-password-here`

From: https://nodered.org/docs/security#editor--admin-api-security
