### ISSUE TITLE
Update Node to v6 (or 8 ???) on aarch64

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red-docker#29]
On aarch64, the version provided still pulls in Node 4, instead of Node 6 like all the rest.

It should be a simple one-line fix to the FROM line in the Dockerfile, but there's a small snag in Node version naming at Docker hub. I don't want to pull in some specific point release of Node, just whatever is latest for 6.

See https://github.com/tianon/jenkins-groovy/issues/21 for the naming issue on Docker hub, and when it gets resolved this will be very easy to resolve as well.

**Comment by dceejay** [comment]
Should this now also be node 8 ? and move to the newer official repo ? https://hub.docker.com/r/arm64v8/node/

https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by dceejay** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red. 

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
