### ISSUE TITLE
Startup fatal error

### ISSUE THREAD

**Issue by chrizzH** [node-red/node-red-docker#296]
Hello,

I have an issue with starting up the docker image with tag "latest" I see this in my docker console:

>Fatal error in , line 0
>unreachable code
>FailureMessage Object: 0x7ecbd17c

I run docker on Raspberry Pi 3  with raspbian buster.

**Comment by hardillb** [comment]
Please make sure you use the template you were shown when opening issues, it gathers a lot of information we need to be debug problems.

This appears to be down to a change in the alpine container that the NodeJS container we use is based on.

Adding the following to the docker run command will get it working `--security-opt=seccomp=unconfined`

e.g.

     docker run --d --security-opt=seccomp=unconfined -p 1880:1880 -v /some/path:/data nodered/node-red:latest

I'm looking for a permanent fix.

**Comment by hardillb** [comment]
builds pushed to docker hub. with version 2.1.4-1 and all the latest-* versions
