### ISSUE TITLE
[warn] Cannot find Pi RPi.GPIO python library

### ISSUE THREAD

**Issue by makeacoffeeprj** [node-red/node-red-docker#31]
Hi,

when I try to run the node-red-docker rpi image, there's the following warning in the log:

18 Jun 18:07:18 - [warn] Cannot find Pi RPi.GPIO python library
18 Jun 18:07:21 - [warn] ------------------------------------------------------
18 Jun 18:07:21 - [warn] [rpi-gpio] Warning : Cannot find Pi RPi.GPIO python library
18 Jun 18:07:21 - [warn] ------------------------------------------------------

How is it possible to enable GPIO library, as I want to use node-red to interact with the gpio of the raspberry?

Thanks,
Diego

**Comment by makeacoffeeprj** [comment]
I had to do an apt-get update && apt-get install python-rpi.gpio

**Comment by jthomas** [comment]
Thanks for reporting this. 
@dceejay should we add this lib to the base RPi image?

**Comment by dceejay** [comment]
yes please.
Though I suspect there are other difficulties with permissions in order to get he pins seen by the host.

**Comment by jthomas** [comment]
I've added this to the base image and re-published the image. 
Thanks for reporting this @makeacoffeeprj 💯
