### ISSUE TITLE
Docker-custom build fails on ssh-keyscan

### ISSUE THREAD

**Issue by alex-vyverman** [node-red/node-red-docker#331]
Hi all,

## So you have a real issue to raise...

Trying to build a custom Docker image using the Docker-custom files provided

### What are the steps to reproduce?

1. git clone https://github.com/node-red/node-red-docker.git
2. cd node-red-docker/docker-custom
3. ./docker-debian.sh

### What happens?
The build fails on:
`ssh-keyscan failed, no more retries left
The command '/bin/sh -c ./known_hosts.sh /etc/ssh/ssh_known_hosts && rm /usr/src/node-red/known_hosts.sh' returned a non-zero code: 1`

### Please tell us about your environment:

[ ] Platform/OS: Ubuntu 20.04

**Comment by hardillb** [comment]
Please show more of the build output,

**Comment by hardillb** [comment]
It's working fine for me with a clean checkout. Does the machine you are running it on have access to the internet?

**Comment by alex-vyverman** [comment]
Thanks for your response.

I tried it on my home network, and it built just fine. 
On the company network we have some security proxy thing which I suspect is messing up the gpg keys.

I'll close this for now.
