### ISSUE TITLE
Entrypoint.sh is missing execution permissions

### ISSUE THREAD

**Issue by jean-paullizotte** [node-red/node-red-docker#339]
Fairly straightforward, when I try to run a built container with the "docker-custom\docker-debian.sh" script.
The "docker-custom\Dockerfile.debian" seems to be missing a `RUN chmod +x ./entrypoint.sh` in it.

**Comment by hardillb** [comment]
The `entrypoint.sh` file should already have execute permission set when checked out of the repo and that should carry over when copied into the container.

It shouldn't need to be explicitly set

It's working as expected when I run the `docker-demian.sh` script on my Fedora machine.

What environment are you running the build script?

(In future please fill out the full template you are presented with when opening an issue, it collects all the information we need to work on problems.)

**Comment by jean-paullizotte** [comment]
I'm running it on raspberry pi OS. I'm using a NFS remotely shared folder, for the root of the build, if that has any incidence. 
Is there any harm in adding it just in case?

**Comment by hardillb** [comment]
Do the files in the `docker-custom/scripts` directory have the execute bits set when checked out?

**Comment by jean-paullizotte** [comment]
I tried a git clone from a different machine and the execute bits are there!
I have no clue, why.

**Comment by hardillb** [comment]
Please look at the nfs mount options in the `/etc/fstab` for the mount in question on the pi with the build problem, looking for the `noexec` option
