### ISSUE TITLE
ssh-keyscan failed, no more retries left

### ISSUE THREAD

**Issue by songzh96** [node-red/node-red-docker#341]
Hi ,
when I run .docker-debian.sh, 

Linux ： arm32v7
Error Logs:
```
# vs-ssh.visualstudio.com:22 SSH-2.0-SSHBlackbox.10
# vs-ssh.visualstudio.com:22 SSH-2.0-SSHBlackbox.10
# vs-ssh.visualstudio.com:22 SSH-2.0-SSHBlackbox.10
# vs-ssh.visualstudio.com:22 SSH-2.0-SSHBlackbox.10
# vs-ssh.visualstudio.com:22 SSH-2.0-SSHBlackbox.10
ssh-keyscan failed, no more retries left
The command '/bin/sh -c ./known_hosts.sh /etc/ssh/ssh_known_hosts && rm /usr/src/node-red/known_hosts.sh' returned a non-zero code: 1
```

**Comment by hardillb** [comment]
What happens if you run the following command on your docker build machine?

```
ssh-keyscan -o 2022 source.developers.google.com
```

Also where in the world is the docker build machine?

**Comment by songzh96** [comment]
> 
Hi , this is feedback
unknown option -- o
usage: ssh-keyscan [-46cDHv] [-f file] [-p port] [-T timeout] [-t type]
                   [host | addrlist namelist]

China

**Comment by songzh96** [comment]
```
ssh-keyscan  2022 source.developers.google.com
source.developers.google.com: Connection closed by remote host
source.developers.google.com: Connection closed by remote host
source.developers.google.com: Connection closed by remote host
source.developers.google.com: Connection closed by remote host
source.developers.google.com: Connection closed by remote host
```

**Comment by hardillb** [comment]
Sorry, typo

The `-o` should be `-p`

I wonder if access to `source.developers.google.com` is blocked by the Chinese Government.

In that case I suggest you edit the `know_hosts.sh` file to remove the key import for that host.

**Comment by songzh96** [comment]
![image](https://user-images.githubusercontent.com/26770241/208441280-e0401d9d-b551-4295-9557-410484f84e38.png)

Hi, I delte you said.
but it not successed. 
it still error

**Comment by hardillb** [comment]
Please don't post images of code, post the actual code and format it (wrap it in tripple back ticks `)

You appear to have removed a lot more than I mentioned. You should ONLY remove line 40

```
    ssh-keyscan -p 2022 ${hosts_2022} >> ${known_hosts_file}
```

and line 53

```
256 SHA256:AGvEpqYNMqsRNIviwyk4J4HM0lEylomDBKOWZsBn434 [source.developers.google.com]:2022 (ECDSA)
```

**Comment by songzh96** [comment]
it work's!!!!
Thank you very much!!!

👍 

Best Regards
Songzh
