### ISSUE TITLE
Cannot build custom docker due to known_hosts.sh failling

### ISSUE THREAD

**Issue by fbbln** [node-red/node-red-docker#344]
### What are the steps to reproduce?
Clone repository off of github, run script
docker-alpine.sh or docker-debian.sh
in the folder docker custom.

### What happens?
Build fails with message:
#10 3.854 ssh-keyscan failed, no more retries left

### What do you expect to happen?
I expect the build script not to fail.

### Checks done already
- It seems that "source.developers.google.com" is not reachable by ssh-keyscan on port 2022 or default

### Please tell us about your environment:

[ ] Platform/OS: Windows 10, WSL2, Docker Desktop with Engine v20.10.17

**Comment by fbbln** [comment]
It works once the keyscan for the above mentioned domain is commented out.

**Comment by hardillb** [comment]
Duplicate https://github.com/node-red/node-red-docker/issues/34

Are you in China? This is a problem with your government firewall blocking access to Google's source code platform.

**Comment by fbbln** [comment]
No. Location is DE.
I can reach the domain using browser but it redirects me to https://source.cloud.google.com/onboarding/welcome.

Yet, it seems the company firewall is the issue, blocking port 2022 by default.

**Comment by hardillb** [comment]
OK, still the same problem, blocked by local firewall.

You can either comment out the Google domain or extend the published containers to build a custom image.

**Comment by fbbln** [comment]
I commented out the domain.
I need an image without healthcheck to run on my Synology and the run command there seems to ignore the "--no-healthcheck" option. So extending the published image is not an option.

**Comment by hardillb** [comment]
Why do you need to remove the healthcheck? it's part of the Docker spec and should work everywhere.

**Comment by fbbln** [comment]
My usecase is just some basic home-automation with not much action when nobody's home or at night.
Healthcheck is running every 30s and writing its status to disk. This effectively keeps the disks in the Synology spinning all the time.
As the system is basically idle for 12+h/day, there's no need for the disks to keep spinning and waste 10W ...

By disabling healthcheck I hope to overcome this. Passing --no-healthcheck or a different interval to docker run did not seem to work.

**Comment by hardillb** [comment]
OK, so this is specific to your use case, not some generic Synology error we need to fix.

As you are already editing the Docker file to remove the healthcheck then removing the Goolge git server from the keyscan section is sensible solution.

**Comment by fbbln** [comment]
Well, this is an issue often encountered with Synology or similar NAS (the web is full of such issues).
So it may make sense to publish a "non-healthcheck"-Version...
In the Dockefile.custom the healthcheck is disabled anyway, so I just had to remove the Google Server.
