### ISSUE TITLE
Docker prim/sec DNS failover

### ISSUE THREAD

**Issue by p4r4ll4x** [node-red/node-red-docker#348]
### What are the steps to reproduce?
Setup 2 DNS servers in docker.

### What happens?
Nodered sticks to 1 of the 2 DNS servers, if that DNS server goes down, connections with DNS name fail.

### What do you expect to happen?
Expected behavior is that Nodered switches to the alternate DNS server when the other goes down.
Sometimes i see Nodered using the secondary DNS server and it does not switch back to the primary when the secondary goes down.

### Please tell us about your environment:

    
![2023-02-17 15_10_49-Portainer _ vDocker-2021](https://user-images.githubusercontent.com/33659698/219678348-b0bb2820-3dc2-4d4b-b096-150451dd6f16.png)

**Comment by goessensj** [comment]
> Can you try with the debian based container please (you will have to build it yourself until 3.1.0 ships, instructions at https://github.com/node-red/node-red-docker/tree/master/docker-custom )
> 
> I think this might be a bug in the Alpine libc DNS resolver and not something we are likely to be able to do much about)

I prefer to wait to fixed this. When is 3.1.0 expected?
Will the docker container be debian based by default from 3.1.0?

**Comment by hardillb** [comment]
No, we will probably be offering an additional build based on a Debian image.

There is no time frame for when 3.1.0 will ship yet, while the first beta has shipped it will depend on what bugs are found and how much time the team gets to work on things.

But please do build a the Debian based container and test it, this is only a guess based on some other DNS issues that have been seen with the Alpine based containers, without testing we have no way to know if this actually a solution and if it's not then we will end up starting from scratch once 3.1.0 ships.

**Comment by bella-wmi** [comment]
Hey, im facing similar issues with the DNS inside the node-red-docker. We are using a custom defined docker network for our node-red docker. Therefore the docker embedded DNS is used and forwards the request to the dns server configured on the host system. If we configure multiple DNS nameserver on our host system all of them get used, when increasing the dns timeout inside the docker. However the DNS record is not cached which result in multiple dns request on a request like a ping. This slows down the response time of http requests.  Additionally when I start the docker container and connect it to another docker network it also does not work. 

Have you seen similar behaviour ?

**Comment by hardillb** [comment]
@bella-wmi again, probably down to the Alpine muscl-libc DNS implementation and the same suggestion, build the Debian based container and test it.

**Comment by bella-wmi** [comment]
@hardillb tested it with the Debian based docker. It works fine. The dns is cached and it works fine.
