### ISSUE TITLE
ERROR [release 4/7] RUN npm config set python which python3 --global

### ISSUE THREAD

**Issue by keerio** [node-red/node-red-docker#352]
### What are the steps to reproduce?

Build a docker

### What happens?

npm config set python no longer supported by npm as of npm v9.0.0
https://github.com/nodejs/node-gyp/issues/2798
so
https://github.com/node-red/node-red-docker/pull/336
throws an error now

 => [release 3/7] RUN npm config set cache /data/.npm --global                                                                                                            1.3s 
 => ERROR [release 4/7] RUN npm config set python `which python3` --global 

### Please tell us about your environment:

[ ] Platform/OS:

[ ] Browser:
 
  - If you are a Portainer user, please attach a screenshot of your container details.
  
    ```
    Containers -> Click on the node-red container -> Scroll to Container Details and take a screenshot
    ```
    
  - If you are a command line user please execute the following command and attach the log file.

    ```shell
    docker inspect <container_id> > container.log
    ```

**Comment by hardillb** [comment]
Please supply a lot more information about what you mean by `build a docker`

**Comment by hardillb** [comment]
Building with the default options works just fine, what options did you change?
