### ISSUE TITLE
Define niceness of the process - High priority

### ISSUE THREAD

**Issue by thalesmaoa** [node-red/node-red-docker#366]
I'm running the nodered docker container.  I noticed that decrease priority is easy with docker commands. However, increase priority I must use nice. Is there a way to implement it inside the container?

```
$ ps -axl | grep node-red
4  1000  4123  4054  20   0 254804 129280 -     Rl   ?         18:09 node-red
```

Now, it is set to `0`. I want to set it to `-19`.

**Comment by dceejay** [comment]
I don't think you can set this within the container... but it's more of a docker question than Node-RED so the experts on docker may know different.
