### ISSUE TITLE
Docker images on the Hub are 9 months out of date / not regularly published even when there isn't a Node Red update

### ISSUE THREAD

**Issue by webash** [node-red/node-red-docker#367]
I was asked to published this by @knolleary in [this thread on the forums](https://discourse.nodered.org/t/docker-hub-images-havent-been-updated-in-9-months/77805). Happy to try help with this issue if someone has the time to handover existing process to me.

### What are the steps to reproduce?
Visit [the Docker Hub for Node Red](https://hub.docker.com/r/nodered/node-red/tags)

### What happens?
The latest published images are 9 months old.

### What do you expect to happen?
The images should be republished as often as any downstream image (eg, Alpine) are pushed to ensure that updates in that dependency are included in the node-red images.

### Please tell us about your environment:

[ ] Platform/OS:
Docker

[ ] Browser:
N/A
 
  - If you are a Portainer user, please attach a screenshot of your container details.
  
    ```
    Containers -> Click on the node-red container -> Scroll to Container Details and take a screenshot
    ```
    
  - If you are a command line user please execute the following command and attach the log file.

    ```shell
    docker inspect <container_id> > container.log
    ```

**Comment by deschmih** [comment]
I fully agree to @webash , node-red image should republished in a timely constant manner for solving critical and high CVE's . The actual image on docker hub contains many of high and critical CVE's which are allreday fixed by other's in past.

**Comment by webash** [comment]
I think (as an outsider, but a long-term Node Red user) latest release of Node Red being the only regularly rebuilt version only is a fair position; people shouldn't expect support for older versions in an OSS project, and ultimately if they _need_ an older version for some reason, they likely have a complex environment that should justify them building their own container on a regular basis (for upstream fixes), targeting whichever explicit older version (of node red) that they like. Average users will be the most vulnerable, and likely `:latest` without knowing much about how containers work, nor about the security issues inherent with them. Thus, ensuring at least that `:latest` (and `:current.version.number` if it is separate image) is regularly rebuilt should cater for improving most scenarios.

Most actively developed open source projects with official containers seem to rebuild their containers (at least) weekly; which I imagine is fine if that is automated via Github Actions or similar; but if you're needing to do it manually due to complexities then I suspect that becomes unwieldly. Happy to help with automated rebuilds/pushes if that's the part that holds back more frequent rebuilds.

number/naming seems like a complicated space, so I'd forgive leaving that to a later time. Potentially my only preference would be to have `:latest` point to the `:current.version.number` image, so that the hashes match, giving those who care the ability to inspect such; but I'm coming at this suggestion with 'reckons' rather than experience.

**Comment by hardillb** [comment]
I have just re-spun the 3.0.2 docker container, it is using the same lags as when it was released (and is tagged as latest).

At this point it's going to be a manual process. The GitHub action that builds the containers needs a pretty major overhaul soon (due to using deprecated methods for setting variables for later steps). Once 3.1.0 releases I'll look at doing that and then see if we can safely automate the re-spin action.

Please give the new images a quick test

**Comment by A-Ghorab** [comment]
Hello @hardillb 

This new docker version broke our build system as we were depending on manifest info provided by docker hub 

for example node red 2 still have this manifiest info 

https://registry.hub.docker.com/v2/nodered/node-red/manifests/2.2.3-12

`{
   "schemaVersion": 1,
   "name": "nodered/node-red",
   "tag": "2.2.3-12",
   "architecture": "amd64",
   "fsLayers": [
     .....
   ]
}`

but after the new release we only get OCI files without any manifest for details like node-red version

`{
    "errors": [
        {
            "code": "MANIFEST_UNKNOWN",
            "message": "OCI index found, but accept header does not support OCI indexes"
        }
    ]
}`

**Comment by hardillb** [comment]
@A-Ghorab None of the 2.x images should have been touched at all. Only the 3.0.2 containers where updated.

**Comment by A-Ghorab** [comment]
> @A-Ghorab None of the 2.x images should have been touched at all. Only the 3.0.2 containers where updated.

yes i just took the version 2 as an example to how the previous output was like 

Node-red docker files for version 3 were the same but now they are showing the error i added.

this happened when the new node red files were released.

**Comment by hardillb** [comment]
You are going to need to be a LOT more explicit about what isn't working here. Give clear examples of what is broken, not of things that work.

**Comment by A-Ghorab** [comment]
> You are going to need to be a LOT more explicit about what isn't working here. Give clear examples of what is broken, not of things that work.

yeah my bad for not explaining it well. i suspect it might be an issue related to docker and not related to NodeRed entirely 

ok i was using docker hub to fetch the node-red docker image details like the NODE_RED_VERSION 

this was working fine until the images has been updated it doesn't show the details right now 

steps on how i used to get them

1. get token from https://auth.docker.io/token?service=registry.docker.io&scope=repository:nodered/node-red:pull
2. call this url with token https://registry.hub.docker.com/v2/nodered/node-red/manifests/latest
3. read the result as json and fetch the needed info.

right now when i go through the steps i get an error 
```json
{
    "errors": [
        {
            "code": "MANIFEST_UNKNOWN",
            "message": "OCI index found, but accept header does not support OCI indexes"
        }
    ]
}
```

the docker image it self is working fine for me nothing to it but the manifest section is the one affected by the changes.

Thanks

**Comment by hardillb** [comment]
@A-Ghorab I don't think this is directly related to the images, it looks like it's a change in the Docker registry.

The error appears pretty explicit, you need to include the right `Accept` header in the request

e.g.

```bash
!/bin/sh
TOKEN=`curl 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:nodered/node-red:pull' | jq -r .token`

echo $TOKEN

curl -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.oci.image.index.v1+json" https://registry.hub.docker.com/v2/nodered/node-red/manifests/latest
```

**Comment by A-Ghorab** [comment]
> @A-Ghorab I don't think this is directly related to the images, it looks like it's a change in the Docker registry.
> 
> The error appears pretty explicit, you need to include the right `Accept` header in the request
> 
> e.g.
> 
> ```shell
> !/bin/sh
> TOKEN=`curl 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:nodered/node-red:pull' | jq -r .token`
> 
> echo $TOKEN
> 
> curl -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.oci.image.index.v1+json" https://registry.hub.docker.com/v2/nodered/node-red/manifests/latest
> ```

ok to continue with my finding i did add the oci accept header 

and it's returning 

```json
{
    "mediaType": "application/vnd.oci.image.index.v1+json",
    "schemaVersion": 2,
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:84db99f5c4615f146062003f8d8e1aa308c4337b6df9d5fd4668895650c8c94e",
            "size": 3515,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:62f08e056160228e266f6c14be1e209b7f311ee71aecc077febdba4b06b206b1",
            "size": 3515,
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:82847397f18ff6e55ac4d7beb53bdfd8b020b11105bdd868a28798bdce32cd54",
            "size": 3515,
            "platform": {
                "architecture": "s390x",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:34afae6774ec941f2d8a67e3a8dc5cbfe174e9ea6f729dae14134e7b5299f4b5",
            "size": 3514,
            "platform": {
                "architecture": "arm",
                "os": "linux",
                "variant": "v7"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:127fb2fae8107330011aa116bbd783d5267da37b947e2d43c3fbc69f26bc0345",
            "size": 3514,
            "platform": {
                "architecture": "arm",
                "os": "linux",
                "variant": "v6"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:84ee479069d685fb57d5e8e84be61b11fb3d33f0cb977045eb4c192d47658d9b",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:84db99f5c4615f146062003f8d8e1aa308c4337b6df9d5fd4668895650c8c94e",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:86129e8f937b3f9b80dbc3baa5fd532bc062b7ebd2e3580aa2d562fa304e0c52",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:62f08e056160228e266f6c14be1e209b7f311ee71aecc077febdba4b06b206b1",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:2f295f7cca9ce85057f16994a84feb7edf3b3c7e6d2c3c7324de2c1e2e959dea",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:82847397f18ff6e55ac4d7beb53bdfd8b020b11105bdd868a28798bdce32cd54",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:c60e7cee17da3cd23aab8a93c052a426bafebadea0d97907c79ac924d65a3d6a",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:34afae6774ec941f2d8a67e3a8dc5cbfe174e9ea6f729dae14134e7b5299f4b5",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:4def48e1f8e543160db7de851b6674e290ca799a4b99045a878f52dd7397bee9",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:127fb2fae8107330011aa116bbd783d5267da37b947e2d43c3fbc69f26bc0345",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        }
    ]
}
```

it doesn't include the history section that i used to relay on to fetch the node-red version from the image 

ok just to be clear maybe you can guide me, 

Is there a way to fetch the current node-red version and nodejs version used inside the docker image? as this is what i'm trying to get.

Thanks

**Comment by hardillb** [comment]
@A-Ghorab No idea, you'll have to explore what the Docker registry API offers

At this point this is not something the Node-RED team have any influence over, the imagers were built and pushed using pretty much the exactly the Docker build/push GH Action.

**Comment by A-Ghorab** [comment]
@hardillb yeah thanks for the help i did find a way out using docker hub :) 

just one thing i noticed when i was checking the env for the images 

```json
[
"NODE_VERSION=16.20.0",
"YARN_VERSION=1.22.19",
"NODE_RED_VERSION=master",
]
```

the NODE_RED_VERSION is set to master shouldn't it be 3.0.2 ?

Thanks

**Comment by hardillb** [comment]
@A-Ghorab #376 should fix that when it gets merged I'll respin the builds again

**Comment by hardillb** [comment]
Containers rebuilt again, please check

**Comment by BloodBlight** [comment]
Just curious about the state of this.  I was trying to get nodejs updated not realizing 16 was baked into the image.  V16 is no longer the recommended version and there is at least 1 pallet that will not install due to the age of nodejs.

**Comment by hardillb** [comment]
There is a build available with nodejs 18 `latest-18`

The  versions on nodejs will be updated with the release of - Node-RED v4. We can not change the version that is tagged as `latest` without a major version bump as it is a breaking change (node modules with native components will need to be rebuilt)

**Comment by hardillb** [comment]
I'm going to close this now as there is a mechanism to rebuild the latest releases to pick-up upstream fixes (e.g. from alpine) when required.

**Comment by webash** [comment]
In case I wished to selfishly 'borrow' such a mechanism myself for my own projects, could you share the commit / file changes made to get this working?

**Comment by hardillb** [comment]
@webash https://github.com/node-red/node-red-docker/commit/d6276872ad3ffd0a260b817e06dc4aebb56c1879
