### ISSUE TITLE
No matching manifest for windows/amd64

### ISSUE THREAD

**Issue by biohazardxxx** [node-red/node-red-docker#368]
Tried to get a nodered container under windows server with docker.
Did run
    ```shell
    docker run -p 1880:1880 -it -v "nodered/data" nodered/node-red
    ```
    and get:
Unable to find image 'nodered/node-red:latest' locally
latest: Pulling from nodered/node-red
docker: no matching manifest for windows/amd64 10.0.20348 in the manifest list entries.
See 'docker run --help'.

Also via portainer I get issues for unsupported capabilities.

**Comment by hardillb** [comment]
We do not publish a windows native build, all our builds are Linux based

**Comment by biohazardxxx** [comment]
Ok thanks, will see if I build my own or go Linux.
