### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c ./known_hosts.sh /etc/ssh/ssh_known_hosts && rm /usr/src/node-red/known_hosts.sh" 

### ISSUE THREAD

**Issue by Jeka95** [node-red/node-red-docker#380]
14:14:49 Dockerfile.custom:38
14:14:49 --------------------
14:14:49   36 |     # Setup SSH known_hosts file
14:14:49   37 |     COPY known_hosts.sh .
14:14:49   38 | >>> RUN ./known_hosts.sh /etc/ssh/ssh_known_hosts && rm /usr/src/node-red/known_hosts.sh
14:14:49   39 |     RUN echo "PubkeyAcceptedKeyTypes +ssh-rsa" >> /etc/ssh/ssh_config
14:14:49   40 |     
14:14:49 --------------------
14:14:49 ERROR: failed to solve: process "/bin/sh -c ./known_hosts.sh /etc/ssh/ssh_known_hosts && rm /usr/src/node-red/known_hosts.sh" did not complete successfully: exit code: 1

**Comment by Jeka95** [comment]
> Can you supply some more details here e.g. the docker build line that you ran to get this error and from what directory you ran it.

![image](https://github.com/node-red/node-red-docker/assets/72086251/c49a1b8a-5f32-45c4-a82e-1f4701335ac3)



if I understood correctly, these values ​​are no longer valid, you updated 2 months ago

**Comment by hardillb** [comment]
If you pull the project again it should build now

**Comment by hardillb** [comment]
3.0.2 builds re-built and available. Closing this now.

**Comment by oilop9000** [comment]
looks like it happened again :(

**Comment by hardillb** [comment]
@oilop9000 You are going to need to supply at least some details here also please open a new issue rather than comment on an old one. When you do, please include the output of the docker build command and the git hash of the repo you are building from, as the current checked in version appears to work fine for me when I test it.
