### ISSUE TITLE
latest is actually NR16 - shouldn't  it be 18?

### ISSUE THREAD

**Issue by sgofferj** [node-red/node-red-docker#390]
I just ran into some issues updating my palette and according to the log, a bunch failed to install because they expect NR18. I'm using the nodered:latest container. A quick look at the docker hub revealed that latest is not -18 but -16.

latest: 81bc011a753112fa0abbaeb4d6e8e3f80e102ec7ff0ee816dc411515b7804c17
latest-16: 81bc011a753112fa0abbaeb4d6e8e3f80e102ec7ff0ee816dc411515b7804c17
latest-18: babcb0914240a81fdab6b217a29e0d09cc7369344b1e1b6fdde411ff3c02dcb0

Is that an oversight or intended? :smile:

**Comment by hardillb** [comment]
No, this is intended. We will be changing the default with the 4.0.0 release
