### ISSUE TITLE
Image with Debian and 18

### ISSUE THREAD

**Issue by AndreKR** [node-red/node-red-docker#392]
Node.js 16 is getting pretty old and there are nodes on npm that don't support 16 anymore.

Would it be possible to bump the Node.js version of the Debian images to 18?

**Comment by hardillb** [comment]
NodeJS version bumps will happen in Node-RED 4.0

**Comment by AndreKR** [comment]
Depending on when that will happen, would it in the meantime be possible to provide "-18" images like there already are for Alpine?

**Comment by hardillb** [comment]
No, we will not be increasing the number of containers we already have to maintain and support.

If you need a container based on NodeJS 18 you can build your own using the scripts in the docker-custom directory

**Comment by hardillb** [comment]
@luixal Please do not use closed issue to report unrelated problems.

This failure implies that one of the git services we pre-populate the container with has changed their SSH keys (again). Please open a new issue and I'll look at it a little later.

**Comment by hardillb** [comment]
@luixal Also I've just run this with the head of the master branch and everything is working as expecting, so when you open the new issue please include a lot more detail about exactly what you did

**Comment by S474N** [comment]
In connection with `latest-debian` and especially the node.js 16 version, I have problem with the installation of NRCHKB :(

https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/552

**Comment by hardillb** [comment]
New versions will ship with Node-RED v4.0
