### ISSUE TITLE
Unable to install node-red-admin

### ISSUE THREAD

**Issue by dulfox** [node-red/node-red-docker#40]
I cannot install node-red-admin because node-red user is not owner of /usr/local/lib/node_modules :

`npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-red-admin"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/node-red/.node-gyp/6.11.0/npm-debug.log`

and the directory is owned by 1001:1001

`$ ls -ltra /usr/local/lib/node_modules
total 12
drwxr-xr-x  3 1001 1001 4096 Jul 18 20:33 .
drwxr-xr-x 11 1001 1001 4096 Jul 18 20:33 npm
drwxr-xr-x  4 1001 1001 4096 Jul 18 20:33 ..`

but node-red user is 1000:1000

`$ id node-red 
uid=1000(node-red) gid=1000(node-red) groups=1000(node-red)`

and I cannot sudo because it asks for a password that I don't know.

`$ sudo su - 
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
[sudo] password for node-red:
Sorry, try again.`

I'm using nodered/node-red-docker:rpi

**Comment by jthomas** [comment]
Hey @dulfox, quick question, can I ask what you're intending to use `node-red-admin` for? If it's just to install extra nodes, the UI now supports this [through the palette](https://nodered.org/docs/getting-started/adding-nodes) since v0.15.

If that doesn't assist, I can look into the issue above.

**Comment by dulfox** [comment]
I have to admit I didn't know that. I had an old tutorial. I have to look into it to see if I can go into it with this "workaround".

BTW, it is strange to let own lots of directories by user '1001:1001' who doesn't exists and not be able to sudo to root. My 2 pences.
