### ISSUE TITLE
Support Node 20

### ISSUE THREAD

**Issue by carefulcomputer** [node-red/node-red-docker#400]
Current recommended version of node for node-red are [node 18 and node 20.](https://nodered.org/docs/faq/node-versions) However this docker repo only provides node 16 and node 18. 
Since several of use packages which rely on newer versions, please also add docker images for node 20.

**Comment by hardillb** [comment]
The move to nodejs 20 will be with the release of Node-RED 4.0

**Comment by carefulcomputer** [comment]
Thanks for quick response. Just wondering if there is some technical issues in supporting node 20 or is it just related to additional effort required ? I can try to make a pull request if there is any interest.

**Comment by hardillb** [comment]
We will not be increasing the number if builds we need to support

**Comment by carefulcomputer** [comment]
Thank you. I recognize the effort required to support multiple build versions. However, for this project, I think it should track the currently recommended versions (as listed on node-red page)  rather than legacy versions that, while still supported, are not up-to-date.
Legacy versions cause other problems (e.g. nodejs package 'got' latest version doesn't support nodejs16, so it makes it impossible to use it in this docker image).
