### ISSUE TITLE
NodeJS Versions need to be updated

### ISSUE THREAD

**Issue by wuast94** [node-red/node-red-docker#436]
this repo builds the nodered container with nodejs 14 16 and 18

https://nodejs.org/en/about/previous-releases

14 and 16 are out of  maintainance 
18 is in maintenance which ends next year
the current LTS version is 22

why does this repo still defaults to 16?  running under 18 needs special tagging. 

i cant even update to node-red-node-email v3.0.0 (which is an official nodered node) on the default tags because it needs nodejs 18

would be nice to set the new default to 22 because its the actual LTS and remove the 14 and 16 because they are dont even maintained anymore. at least it should defaults to 20: https://nodered.org/docs/faq/node-versions

**Comment by knolleary** [comment]
Hi @wuast94 

We treat changes to the default node.js version as a major version change, which has blocked us from updating the images in the 3.x stream.

We will be updating all the defaults when we ship Node-RED 4.0 in the **next week** - where the default will be Node 20 which is the current LTS release. (Node 22 doesn't become LTS until October).

We already publish beta versions for Node-RED 4.0 - https://discourse.nodered.org/t/node-red-4-0-beta-4-the-final-one-released/88387 - so you can try it out.
