### ISSUE TITLE
The newest latest didn't support linux/arm/v7 architecture

### ISSUE THREAD

**Issue by SuiKaSan** [node-red/node-red-docker#439]
### What are the steps to reproduce?

Pull docker nodered/node-red image with tag latest and specify linux/arm/v7 arch.

### What happens?

Pull failed because of arch not exist.

### What do you expect to happen?

Pull success.

### Please tell us about your environment:

[ ] Platform/OS:

arm/v7

[ ] Browser:
 
  - If you are a Portainer user, please attach a screenshot of your container details.
  
    ```
    Containers -> Click on the node-red container -> Scroll to Container Details and take a screenshot
    ```
    
  - If you are a command line user please execute the following command and attach the log file.

    ```shell
    docker inspect <container_id> > container.log
    ```

**Comment by hardillb** [comment]
This is because building all the 32bit ARM containers (ARMv6 and ARMv7) hangs when run with docker buildx and qemu when running on GitHub Actions.

We are looking at ways to do native builds for 32bit ARM, we will add the builds back when we have a solution.

**Comment by hardillb** [comment]
I have respun the 4.0.2 builds today. There should now be ARMv7 containers in the manifest
