### ISSUE TITLE
Missing ping in 4.0.2-debian image

### ISSUE THREAD

**Issue by napest-droid** [node-red/node-red-docker#444]
### What are the steps to reproduce?
Attach shell of the container, try ping. 

### What happens?
```
node-red@7a9c3f4b61c0:~$ ping
bash: ping: command not found
node-red@7a9c3f4b61c0:~$ apt install iputils-ping
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
node-red@7a9c3f4b61c0:~$ sudo apt install iputils-ping
bash: sudo: command not found
node-red@7a9c3f4b61c0:~$ su
Password: ???
```

### What do you expect to happen?
If the network of the container is bridged with host, expecting ping to hosts local network. 

### Please tell us about your environment:
Raspberry Pi 400

[ ] Platform/OS:
Broadcom BCM2711 quad-core Cortex-A72 (ARM v8) 64-bit SoC @ 1.8GHz
4GB LPDDR4-3200

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

[ ] Browser:
 
[inspect.log](https://github.com/user-attachments/files/16282163/inspect.log)

**Comment by hardillb** [comment]
Ping will be in the container in next release (4.0.3)
