### ISSUE TITLE
Update Nodejs to version 20

### ISSUE THREAD

**Issue by etofi** [node-red/node-red-docker#446]
Node-RED currently [recommends Node 20.x.](https://nodered.org/docs/faq/node-versions )
The container still uses version 18.
Can you please update it to 20.

**Comment by hardillb** [comment]
The Node-RED 4.0.x containers are built with NodeJS 18, 20 and 22 with the `latest` tag using NodeJS 20.

**Comment by xconverge** [comment]
@hardillb yesterday I had to switch from the :latest tag to latest-22 because the latest tag was using node 16 and some of my plugins were not compatible. Just a heads up that I think there is still something weird in the process but didn't think it was worth opening a ticket for...

**Comment by hardillb** [comment]
For a brief period yesterday the latest tags pointed at the 3.1.x builds.

This has now been fixed

**Comment by xconverge** [comment]
> For a brief period yesterday the latest tags pointed at the 3.1.x builds.
> 
> This has now been fixed

Right on, I had bad timing then, just wanted to make sure it was handled and was too busy to open an issue at the time, would have been a waste since you were on it! Thanks!
