### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by braghettos** [node-red/node-red-docker#46]
Hi everyone,

I'm experiencing the "JavaScript heap out of memory" on my flow when I try to receive a HTTP post request.

This is the logging:

> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
> 
> <--- Last few GCs --->
> 
>   185405 ms: Mark-sweep 486.4 (529.0) -> 485.7 (529.0) MB, 7368.5 / 0.0 ms [allocation failure] [GC in old space requested].
>   192804 ms: Mark-sweep 485.7 (529.0) -> 485.3 (529.0) MB, 7398.4 / 0.0 ms [allocation failure] [GC in old space requested].
>   200205 ms: Mark-sweep 485.3 (529.0) -> 495.3 (518.0) MB, 7400.4 / 0.0 ms [last resort gc].
>   207616 ms: Mark-sweep 495.3 (518.0) -> 505.4 (518.0) MB, 7411.3 / 0.0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x29c7c36d <JS Object>
>     1: setTimeout(aka setTimeout) [/usr/src/node-red/node_modules/node-red/nodes/core/core/80-function.js:~146] [pc=0x70e333d4] (this=0x29c081d9 <undefined>)
>     2: arguments adaptor frame: 2->0
>     3: /* anonymous */ [evalmachine.<anonymous>:~1] [pc=0x3c1c99e4] (this=0x712e4659 <JS Global Object>,msg=0x5eeaf835 <an Object with map 0x71cdd7fd>)
>     4: /* anonymous */ [evalmachine.<anonymous>:28] [p...
> 
> Aborted (core dumped)
> 
> npm info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
> npm ERR! Linux 4.9.35-v7+
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data" "--setting" "/data/settings.js"
> npm ERR! node v6.11.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--setting" "/data/settings.js"`
> npm ERR! Exit status 134
> npm ERR! 
> npm ERR! Failed at the node-red-docker@1.0.0 start script 'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--setting" "/data/settings.js"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the node-red-docker package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--setting" "/data/settings.js"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs node-red-docker
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls node-red-docker
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /usr/src/node-red/npm-debug.log
> 

This is the content of npm-debug.log :

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'start',
> 1 verbose cli   '--',
> 1 verbose cli   '--userDir',
> 1 verbose cli   '/data',
> 1 verbose cli   '--setting',
> 1 verbose cli   '/data/settings.js' ]
> 2 info using npm@3.10.10
> 3 info using node@v6.11.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle node-red-docker@1.0.0~prestart: node-red-docker@1.0.0
> 6 silly lifecycle node-red-docker@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle node-red-docker@1.0.0~start: node-red-docker@1.0.0
> 8 verbose lifecycle node-red-docker@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle node-red-docker@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> 10 verbose lifecycle node-red-docker@1.0.0~start: CWD: /usr/src/node-red
> 11 silly lifecycle node-red-docker@1.0.0~start: Args: [ '-c',
> 11 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--setting" "/data/settings.js"' ]
> 12 silly lifecycle node-red-docker@1.0.0~start: Returned: code: 134  signal: null
> 13 info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
> 14 verbose stack Error: node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--setting" "/data/settings.js"`
> 14 verbose stack Exit status 134
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:891:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid node-red-docker@1.0.0
> 16 verbose cwd /usr/src/node-red
> 17 error Linux 4.9.35-v7+
> 18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data" "--setting" "/data/settings.js"
> 19 error node v6.11.0
> 20 error npm  v3.10.10
> 21 error code ELIFECYCLE
> 22 error node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--setting" "/data/settings.js"`
> 22 error Exit status 134
> 23 error Failed at the node-red-docker@1.0.0 start script 'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--setting" "/data/settings.js"'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the node-red-docker package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--setting" "/data/settings.js"
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs node-red-docker
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls node-red-docker
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

This is how I run my container:

`docker run -d -p 1881:1880 --name mynodered --device=/dev/serial0 --user=root -e NODE_OPTIONS="--max_old_space_size=512" --log-opt max-file=2  --log-opt max-size=2k braghettos/node-red-docker:0.17.5-rpi`

I've enabled HTTPS in settings.js file .

Many thanks in advance,

Diego

**Comment by knolleary** [comment]
Are you running this on a Pi? If so, what model?

You could try with a lower max_old_space_size setting so that node's garbage collection kicks in earlier.

**Comment by makeacoffeeprj** [comment]
Hi @knolleary yep it's running on a Pi3. I just tried with a setting of 128, nothing changed.

**Comment by dceejay** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

Closing as we no longer support node.js 6.x - please reopen a new issue if still a problem.

There are a few changes to the new release, please read the README for further details.
