### ISSUE TITLE
Use of USER prevents installation of additional tools

### ISSUE THREAD

**Issue by codeaholics** [node-red/node-red-docker#50]
The use of the `USER` directive prevents extending the image to install additional tools.

I would like a Dockerfile that looks like this:

```
FROM nodered/node-red-docker:0.17.5

RUN apt-get install some-extra-tools
```

But this fails because the `apt` command is run as the `node-red` user which doesn't have permissions to install new software.

I notice also #9 which details other issues with the use of the `USER` directive. In my experience, unless there's a very good reason, it's more usual to not include a `USER` directive, instead allowing the system administrator to specify what user they want the container processes to run as using the `--user` command line switch to `docker run`.

This can be worked around by adding `USER root` before the `apt-get`, but that's a bit nasty and just adds more noise and layers.

**Comment by jthomas** [comment]
Hello @codeaholics. Thanks for the explanation of the issue.

I'm not a Docker expert but did attempt to follow documented Docker best practices when creating these images. This still includes ["If a service can run without privileges, use USER to change to a non-root user."](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user) from the Docker home page. Do you know if this advice has changed? 

I've seen this has created issues for some users but if that advice above is still relevant, we'd have to make a decision on whether this was more important that the security concerns.

NodeRED has a diverse community of users including lots of less technical users. I think overall we'd err on the side of "more secure by default" even though this does inconvenience users who are more advanced. 

If you are already creating a new image to install extra tools, is adding the `USER` commands a burden?

I will definitely add this to the documentation if we don't change the build image to help others overcome this issue.

**Comment by janvda** [comment]
The following worked for me.

```
FROM nodered/node-red-docker:rpi-v8

# installing an editor
USER root
RUN apt-get update && apt-get install nano 
USER node-red
```

**Comment by RaymondMouthaan** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This closes this issue. For custom docker images please have a look the corresponding [README](https://github.com/node-red/node-red-docker/blob/master/docker-custom/README.md)

note: Node-RED images are Alpine based.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
