### ISSUE TITLE
node-red-admin blocked by proxy

### ISSUE THREAD

**Issue by ghost** [node-red/node-red-docker#54]
Hi

As per your README I've installed node-red-admin on the host OS using npm with proxy config and it can see the container's nodes fine on localhost:1880

The issue is when I go to search or install, it comes up with:

```
$ node-red-admin target
Target: http://localhost:1880

$ node-red-admin search node-red-contrib-soap
Error: tunneling socket could not be established, cause=write EPROTO 140418686146624:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:```

**Comment by knolleary** [comment]
What proxy config have you got? Need more details to understand your environment.

**Comment by dceejay** [comment]
Closed as no response to  followup questions.
