### ISSUE TITLE
Running in AWS, best practise for settings.js changes?

### ISSUE THREAD

**Issue by QAnders** [node-red/node-red-docker#57]
This is not solely for AWS I guess but what would be the best approach for changing server settings(.js) after deployment in runtime?

1) Change settings locally, rebuild Docker container and redeploy?
2) Access running server(s) and change in "runtime" and change in local Docker container for next deploy?

#2 is, of course, better from a downtime perspective but it doesn't feel "right" to change in a running container/server...

Also, is there any "runtime change" API/SDK planned for node-red that you would know of (to be able to change settings without changing settings.js)?

**Comment by jthomas** [comment]
1 seems like the best approach. Is there a reason this is not preferable over 2?

**Comment by QAnders** [comment]
Sorry for the late comeback... Well, option 2 won't require a redeploy, just a restart of Node-Red obviously... Just figured if you had any previous experiences/recommendations... :)
