### ISSUE TITLE
Move to Node v8?

### ISSUE THREAD

**Issue by jthomas** [node-red/node-red-docker#62]
Current Dockerfiles are built using Node.js 6 as the major version base image.
Should we be moving to 8 as 6 enters maintaince LTS mode in April? @knolleary 
https://github.com/nodejs/Release

**Comment by dceejay** [comment]
Yes - we test on 8 so should be Ok. (and default to 8 for clean install on Pi)
(just not 9 yet)

**Comment by knolleary** [comment]
Yes, we should do this. The question is how to going about it from a versioning perspective. Don't want to catch downstream users out by making a major version change they then pickup unawares.

We currently push tagged versions `slim`, `pi` and `latest`. Using `slim` for the rest of this, but assume it applies to `pi` and `latest` as well.

How about we start producing `slim-v6`, `slim-v8` etc and have the `slim` point to `slim-v6` for now - that way v8 is available but not the default.

We can then publicise a point where `slim` (etc) will point to `slim-v8`. Anyone who cares about using v6 can update their images to continue to use `slim-v6`.

We can then follow that pattern with v10 in the future.

Thoughts? Already had one request for a v8 docker image from our friends in Hyperledger land - so keen to get something done.

**Comment by jthomas** [comment]
That is a good suggestion. I'll look into this and open a PR.

**Comment by dceejay** [comment]
Re Pi - (and the version of node issue - #60 -  can it pickup a different package.json also ? )

**Comment by knolleary** [comment]
I think #60 represents a much bigger change to how the image runs on Pi - don't want to block doing v8 support whilst sorting out the details for the pi.

**Comment by dceejay** [comment]
Actually - experimenting some more - don't need to change package.json specially for Pi - so yes carry on... though I would suggest removing suncalc and base64 from there... easy enough to install as extras if needed later.  
I do like random though... often use it for demos...

**Comment by jthomas** [comment]
I've updated the travis file to build both new images and push to Docker Hub.
https://hub.docker.com/r/nodered/

Readme has details on the new images availabe. 

Travis file is getting a bit messy with number of builds and tags. It will be simplified once we drop producing v6 builds in the future.

**Comment by flamingm0e** [comment]
I don't see these tags on dockerhub?  When I try to pull latest-v8 it says it doesn't exist.

**Comment by jthomas** [comment]
I've used a slightly different tagging scheme - so now we have `node-red-docker-v8:latest`.
https://hub.docker.com/r/nodered/node-red-docker-v8/tags/

**Comment by knolleary** [comment]
@jthomas sorry I've been too busy to look at this. Now that I have, I don't see any explanation of why publishing three different images is better than doing it all via tags. Had hoped we would discuss my suggestion before committing to any particular solution.

**Comment by jthomas** [comment]
@knolleary Looking back at the prior discussion, I can't now remember why I choose to create new images rather than tags 😯 Let me fix up the travis file to revert to that solution instead.

**Comment by flamingm0e** [comment]
So this will be moving back to tags?  I am so confused.  LOL

**Comment by jthomas** [comment]
@flamingm0e We're moving back to tags, which was the original idea. Once this build has finished, they will be available: https://travis-ci.org/node-red/node-red-docker
