### ISSUE TITLE
Raspberry install breaks

### ISSUE THREAD

**Issue by Head** [node-red/node-red-docker#67]
I'm trying to get this running on my Raspberry Pi 3 running OSMC.
It took me literally hours to get here (You guys should really improve the README. If you don't have docker experience you don't understand what ` $ docker build -f <version>/Dockerfile -t mynodered:<version> .` should be!). What I've done now:
- git clone this repo, cd into it and run `docker build -f rpi/Dockerfile -t nodered/node-red-docker:rpi .`
But now I'm getting:

npm info lifecycle bcrypt@1.0.3~install: bcrypt@1.0.3

> bcrypt@1.0.3 install /usr/src/node-red/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

The command '/bin/sh -c npm install' returned a non-zero code: 1

**Comment by knolleary** [comment]
Hi,

the README goes into great detail about how to use the docker images we provide, including how to extended it within your own images. 

It may assume you have some familiarity with docker once you get into the more advanced topic of creating your own custom images from scratch - so if you have any specific feedback on the README that would be great.

Is there a reason you're trying to build it yourself rather than use the pre-built image we publish to dockerhub - `nodered/node-red-docker:rpi`?

**Comment by Head** [comment]
I'm answering here for the docker part:

> If you want to run the dockerized version of NR on your Pi, you should just be able to run:
> 
> `docker run -it -p 1880:1880 --name mynodered nodered/node-red-docker:rpi`

Oh wow! That's working! Thank you! I've tried `stuff` for 3h or so...
`Is there a reason`... No, beside I have 0 background with docker.

The way of doing it was: I went to https://nodered.org/docs/platforms/docker and tried the quick start - what was failing with a strange error. Googling it lead to "ok, ARM does not work here".

Next thing was seeing rpi - uses [RPi-compatible base image.](https://hub.docker.com/r/hypriot/rpi-node/) and clicking that link. Then I've dockered this https://hub.docker.com/r/hypriot/rpi-node/ thing and was confused why nothing is working... Well, because it's NODE only and no node RED.

Then I've clicked on [DockerHub](https://hub.docker.com/r/nodered/node-red-docker/) and was reading: 

> This repository contains Dockerfiles to build different Node-RED Docker images.
> Build these images with the following command...
>     `$ docker build -f <version>/Dockerfile -t mynodered:<version> .`

That was taking me literaly 2h. Tried to put in `rpi` in both `<version>` fields... Nope, I need this "Dockerfile" - but where is it? Already insinde that 700MB download? Not? Do I need to download it? and so on.

In the end I gave up. Not knowing it's that easy to just run `docker run -it -p 1880:1880 --name mynodered nodered/node-red-docker[:<version>]`

ps. thx for fixing the broken link. It's still dead on https://nodered.org/docs/platforms/docker
