### ISSUE TITLE
Image architecture for Pi is incorrect

### ISSUE THREAD

**Issue by zerodivide1** [node-red/node-red-docker#68]
I am having trouble using the `rpi` Docker image in a Docker Stack deployment. When running as a stack, the service reports that the container is trying to run as `amd64`. However, when running as a standalone service, it works fine.

I did a bit of digging and found that the results of `docker image inspect --format '{{.Architecture}}' nodered/node-red-docker:rpi` report `amd64` instead of `arm` as I'd expect. After some research, I think the only way to avoid this and to properly annotate the image as `arm` is to build the `rpi` image on an ARM device and push it to Docker Hub.

Is it possible that the `rpi` image can be pushed via a ARM-based device to properly tag the arch for the image as `arm`?

**Comment by knolleary** [comment]
Hi @zerodivide1 - thanks for the issue.

We build all the images on Travis and use `aarch64/node:4.6-slim` as the base image for the Pi. This creates images that work fine on the Pi.

I have to admit to not being familiar enough with all things Docker to know how to address this issue. 
We don't want to have to manually build images whenever there is a refresh.

**Comment by RaymondMouthaan** [comment]
Hi @knolleary 
When using qemu with travis to build the images and manifest tool to create a manifest list and push it to docker hub, it should be quit easy to maintain different kind architectures and OSes. 

Please consider my node-red-docker project at https://github.com/RaymondMouthaan/node-red-docker and https://hub.docker.com/r/raymondmm/node-red/ where qemu and manifest tool are used for linux-arm, but could be easily extend to others.

**Comment by rcarmo** [comment]
Hi! I regularly do Docker builds for ARM devices (from Pis to the ODROID series) so please be aware that modern quad-core Pis (2, 3, etc.) are `armv7` and that the older ones (single-core B, Zero, etc.) are `armv6l`. The architecture tagging has somewhat converged into `armhf` for new models and `armv6l` for the single-core ones, but QEMU (and sometimes compiler) options are still a bit confusing.

Since the Zero W is still a _very_ popular device, this bites people frequently.

**Comment by dceejay** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red. 

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
