### ISSUE TITLE
configuration not used when pushing/pulling docker image

### ISSUE THREAD

**Issue by openStove** [node-red/node-red-docker#7]
When I make flows, and the push my docker image on dockerhub, and pull and run it somewhere else, the flows are empty.
(objects added via npm are here, but the configuration is not there)

**Comment by jthomas** [comment]
Hello. 

Can you give me all the commands you use to start Node-RED in Docker so I can walk it through locally?

**Comment by openStove** [comment]
I didn't use special command, just docker run -p ... nodered, and after
that docker start norered, docker stop...

2016-09-07 23:46 GMT+02:00 James Thomas <notifications@github.com>:

**Comment by jthomas** [comment]
This should now be possible. 

I've made changes to the container image to remove the default usage of a volume, which means you can persist changes to a new image. 

See [here for details](https://github.com/node-red/node-red-docker/blob/master/README.md#saving-changes-as-custom-image).
