### ISSUE TITLE
latest-v8 tag doesn't exist

### ISSUE THREAD

**Issue by Skaronator** [node-red/node-red-docker#71]
The Node Red documentation says that I could use `slim-v8`, `rpi-v8` or `latest-v8` tags to use Node.js v8 but the `latest-v8` tag doesn't exist.

I can see `slim-v8` and `rpi-v8` here:
https://hub.docker.com/r/nodered/node-red-docker/tags/
but `latest-v8` doesn't exist.

Here is the doc page:
https://nodered.org/docs/platforms/docker

I assume `v8` is equal to `latest-v8`?

**Comment by knolleary** [comment]
Correct. 

I spotted that myself the other day but forgot to fixup the docs.

**Comment by Skaronator** [comment]
It would make more sense to 'fix' the docker tag than updating the docs.

Better consistency IMO. Currently it looks like this:

normal | node 6 | node 8
------------ | ------------- | -------------
slim | slim-v6 | slim-v8
rpi | rpi-v6 | rpi-v8
latest | v6 | v8

**Comment by JonLaliberte** [comment]
v8 seems to pull node-red v18.6 (not latest).

**Comment by dceejay** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red. 

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
