### ISSUE TITLE
Builtin twitter node is outdated

### ISSUE THREAD

**Issue by simonszu** [node-red/node-red-docker#77]
Respecting Twitter's recent API changes/limitations, `node-red-node-twitter` has published version 1.0.1 lately. https://www.npmjs.com/package/node-red-node-twitter
The node-red docker container still installs version 0.1.15, which cannot be upgraded via the "Manage palette" menu, since it is builtin. 

### What are the steps to reproduce?
Download the image, start the container. Look in the "Manage Palette" menu, the twitter node shows up as 0.1.15

### What do you expect to happen?
Two possible solutions:
- The docker image is updated with Twitter node 1.0.1 or
- completely remove the Twitter node, so it is installable and upgradeable via the "Manage Palette" menu

### Please tell us about your environment:
I am using the latest image by the time of writing this issue. This is node-red v0.18.7. OS is Arch Linux, Browser is Google Chrome.

**Comment by knolleary** [comment]
Hmmm, our automated builds don't readily allow for rebuilds of existing node-red versions. Need to figure out how to automate that so we can publish a new version of 0.18.7.

@jthomas - if you happen to have 5 mins to look at this I'd go so far as to wash up your cup that's languishing on your desk.

**Comment by knolleary** [comment]
The newer images for 0.19 will have the working Twitter node in.
