### ISSUE TITLE
Unable to login from domain

### ISSUE THREAD

**Issue by crispy78** [node-red/node-red-docker#85]
- Node-RED version: 0.19.4
- node.js version: 6.14.4
- npm version: 3.10.10
- Platform/OS: Synology DSM 6.2-23739 update 2
- Browser: Firefox (latest), Google Chrome, Safari mobile, Microsoft Edge

Dear community, developers,

I’ve installed the Docker image of NodeRED on my Synology DS 718+, I’ve enabled login. Whenever I’m using my local IP-address, I’ll get a login screen and can login. Whenever I enable port forwarding and try to login from my domain (domain.xxx:1880), I’ll get the login-screen but after each login attempt I’m transferred to the login again. This behavior is on all mentioned browsers (Windows 10) except Safari mobile that is running on my iPhone. With login disabled NodeRED is running fine locally and from the domain. Any idea or suggestion?

**Comment by dceejay** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This probably supersedes this issue as we no longer support nodejs 6.x - please reopen a new one if still an issue.

There are a few changes to the new release, please read the README for further details.
