### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by billimek** [node-red/node-red-docker#86]
Hi, this isn't an 'issue' but for your awareness:

I've created a kubernetes 'helm chart' for node-red based on this docker image, and intend to submit for inclusion to the [official charts repo](https://github.com/helm/charts).  Any feedback or suggestions for this chart would be most welcomed!

The chart is: https://github.com/billimek/billimek-charts/tree/master/node-red

**Comment by knolleary** [comment]
Hi, thanks for sharing. The issue template to I've deleted points at the forum as the best place for non-issue type things to be raised. I'm sure there will be some people in the wider community interested in this.
