### ISSUE TITLE
Since the last update, i get this error, but i don't have an raspvberry pi (iobroker in a container)

### ISSUE THREAD

**Issue by John11Doe** [node-red/node-red-docker#88]
node-red.0 | 2018-10-14 00:19:41.043 | error | 14 Oct 00:19:41 - [error] Error: port in use
-- | -- | -- | --
node-red.0 | 2018-10-14 00:19:41.037 | error | 14 Oct 00:19:41 - [error] Unable to listen on http://127.0.0.1:1880/
node-red.0 | 2018-10-14 00:19:40.881 | warn | 14 Oct 00:19:40 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
node-red.0 | 2018-10-14 00:19:38.549 | warn | 14 Oct 00:19:38 - [warn] rpi-gpio : Cannot find Pi RPi.GPIO python library
node-red.0 | 2018-10-14 00:19:38.527 | warn | 14 Oct 00:19:38 - [warn] rpi-gpio : Raspberry Pi specific node set inactive

**Comment by RaymondMouthaan** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
