### ISSUE TITLE
Mount error /data

### ISSUE THREAD

**Issue by ranrinc** [node-red/node-red-docker#91]
### What are the steps to reproduce?

`mkdir .node_red`
`docker run -it -p 1880:1880 -v ~/.node_red:/data --name mynodered nodered/node-red-docker --user="ubuntu"`

### What happens?

Trying to mount data into my host (ubuntu) since I need to change some config of setting.js. Instead I got this "Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--user=ubuntu\": executable file not found in $PATH": unknown" Unsure on how to proceed since node-red just stop working

### What do you expect to happen?

It will mount upon running the script

### Please tell us about your environment:

- [ ] Node-RED version:latest
- [ ] node.js version:latest
- [ ] npm version:latest
- [ ] Platform/OS:ubuntu 16.04
- [ ] Browser:Firefox

**Comment by NotesTaker** [comment]
Having the same problem. The only way to work around is to start the docker as root which is not an option for me.

**Comment by jhergeth** [comment]
Had the same problem.
My working solution is to give "Everyone" all rights on the shared volume.
i.e.: I have a directory "docker" in the root of my volume and below "docker" are individual subdirectories for each docker container running on my synology. So there now is also a directory "docker/node-red". 
After giving the group "Everyone" all rights in that subdirectory, nodered/node-red-docker runs.

When checking the properties of the files which are created by nodered in this directory, i see that they are owned by a user 1001 which does not exist in my setup.......

In my opinion giving "everyone" all rights in this subfolder is a smaller risk than running nodered as root user.

**Comment by RaymondMouthaan** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
