### ISSUE TITLE
Beta releases are not available on Docker Hub

### ISSUE THREAD

**Issue by beevelop** [node-red/node-red-docker#95]
The official repository already contains some interesting changes, which are tagged with the `-beta.X` suffix. Unfortunately, those tags are currently not available on Docker Hub. To enable Docker enthusiasts to test the upcoming releases beforehand, I'd like to suggest to also publish the Beta releases to Docker Hub.

Additionally, the most recent Beta release could available as a `beta` tag – for the folks out there preferring rough edge technologies.

**Comment by knolleary** [comment]
Acknowledged - this is on the todo list. 

The contributor who helped set up the automatic publishing of new releases isn't available to help on this. So it will require some time and effort to figure out how to do it manually.

**Comment by beevelop** [comment]
With the fancy new beta release being available today (thank you for that): Any news on this issue?

**Comment by RaymondMouthaan** [comment]
@beevelop if you r interested in the beta versions of node-red docker images, please consider my [docker repo here](https://cloud.docker.com/repository/docker/raymondmm/node-red/tags?page=3)

note: #127 is still not merged, but covers betas as well

**Comment by dceejay** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red. 

This closes this issue. (for now - we now have a mechanism in place to make beta versions available - when they are available next time round)

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
