### ISSUE TITLE
Ping command not found

### ISSUE THREAD

**Issue by julionadal** [node-red/node-red-docker#99]
## So you have a real issue to raise...
docker image: nodered/node-red-docker:rpi does not have ping command for "ping node" block.

### What are the steps to reproduce?
deploy "nodered/node-red-docker:rpi" image and use the "ping node"  block.

### What happens?
"ENOENT ping command not found" on de debug output.

### What do you expect to happen?
"ping node" block to work propertly.

### Please tell us about your environment:

- [ ] Node-RED version: 0.19.5
- [ ] node.js version: v6.11.0
- [ ] npm version: 3.10.10
- [ ] Platform/OS  :Linux 6ae469233dbb 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
The Ping node is not preinstalled in this image - I assume you've added it yourself?

There are many nodes we don't preinstall that have dependencies outside of node.js. We don't preinstall all of those dependencies in case someone installs the corresponding node.

**Comment by julionadal** [comment]
Well, i did and also i did not. I imported the data from a standard instalation of node-red. So in ma case  i will have to make may own image or node-red. Thanks.
